/*
 * Natural Science content — ALL IN ENGLISH (D-5).
 * This subject is taught in English; its content is fixed to English and does
 * NOT follow the UI language selector (like Spanish and English subjects).
 * Its i18n keys only exist in EN. Original content.
 */
import type { EjercicioAny } from "../types";

export const ciencias: EjercicioAny[] = [

  // ─── Living things: animal classification ────────────────────────────────
  {
    id: "sci-3-animals-001",
    materia: "ciencias",
    tema: "living_things.animals",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:science.animals.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:science.animals.q1.a" },
      { id: "b", textoKey: "exercises:science.animals.q1.b" },
      { id: "c", textoKey: "exercises:science.animals.q1.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "sci-3-animals-002",
    materia: "ciencias",
    tema: "living_things.animals",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:science.animals.q2.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:science.common.true" },
      { id: "false", textoKey: "exercises:science.common.false" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "sci-3-animals-003",
    materia: "ciencias",
    tema: "living_things.animals",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:science.animals.q3.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:science.animals.q3.l1" },
      { id: "l2", textoKey: "exercises:science.animals.q3.l2" },
      { id: "l3", textoKey: "exercises:science.animals.q3.l3" },
      { id: "r1", textoKey: "exercises:science.animals.q3.r1" },
      { id: "r2", textoKey: "exercises:science.animals.q3.r2" },
      { id: "r3", textoKey: "exercises:science.animals.q3.r3" },
    ],
    respuestaCorrecta: ["l1:r3", "l2:r1", "l3:r2"],
    imprimible: true,
  },
  {
    id: "sci-3-animals-004",
    materia: "ciencias",
    tema: "living_things.animals",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:science.animals.q4.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:science.animals.q4.a" },
      { id: "b", textoKey: "exercises:science.animals.q4.b" },
      { id: "c", textoKey: "exercises:science.animals.q4.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "sci-3-animals-005",
    materia: "ciencias",
    tema: "living_things.animals",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:science.animals.q5.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:science.common.true" },
      { id: "false", textoKey: "exercises:science.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "sci-3-animals-006",
    materia: "ciencias",
    tema: "living_things.animals",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:science.animals.q6.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:science.animals.q6.a" },
      { id: "b", textoKey: "exercises:science.animals.q6.b" },
      { id: "c", textoKey: "exercises:science.animals.q6.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "sci-3-animals-007",
    materia: "ciencias",
    tema: "living_things.animals",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:science.animals.q7.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:science.common.true" },
      { id: "false", textoKey: "exercises:science.common.false" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "sci-3-animals-008",
    materia: "ciencias",
    tema: "living_things.animals",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:science.animals.q8.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:science.animals.q8.a" },
      { id: "b", textoKey: "exercises:science.animals.q8.b" },
      { id: "c", textoKey: "exercises:science.animals.q8.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },

  // ─── Living things: plants ────────────────────────────────────────────────
  {
    id: "sci-3-plants-001",
    materia: "ciencias",
    tema: "living_things.plants",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:science.plants.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:science.plants.q1.a" },
      { id: "b", textoKey: "exercises:science.plants.q1.b" },
      { id: "c", textoKey: "exercises:science.plants.q1.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "sci-3-plants-002",
    materia: "ciencias",
    tema: "living_things.plants",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:science.plants.q2.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:science.common.true" },
      { id: "false", textoKey: "exercises:science.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "sci-3-plants-003",
    materia: "ciencias",
    tema: "living_things.plants",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:science.plants.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:science.plants.q3.a" },
      { id: "b", textoKey: "exercises:science.plants.q3.b" },
      { id: "c", textoKey: "exercises:science.plants.q3.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "sci-3-plants-004",
    materia: "ciencias",
    tema: "living_things.plants",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:science.plants.q4.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:science.common.true" },
      { id: "false", textoKey: "exercises:science.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "sci-3-plants-005",
    materia: "ciencias",
    tema: "living_things.plants",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:science.plants.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:science.plants.q5.a" },
      { id: "b", textoKey: "exercises:science.plants.q5.b" },
      { id: "c", textoKey: "exercises:science.plants.q5.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "sci-3-plants-006",
    materia: "ciencias",
    tema: "living_things.plants",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:science.plants.q6.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:science.plants.q6.l1" },
      { id: "l2", textoKey: "exercises:science.plants.q6.l2" },
      { id: "l3", textoKey: "exercises:science.plants.q6.l3" },
      { id: "r1", textoKey: "exercises:science.plants.q6.r1" },
      { id: "r2", textoKey: "exercises:science.plants.q6.r2" },
      { id: "r3", textoKey: "exercises:science.plants.q6.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r3", "l3:r1"],
    imprimible: true,
  },
  {
    id: "sci-3-plants-007",
    materia: "ciencias",
    tema: "living_things.plants",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:science.plants.q7.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:science.common.true" },
      { id: "false", textoKey: "exercises:science.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "sci-3-plants-008",
    materia: "ciencias",
    tema: "living_things.plants",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:science.plants.q8.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:science.plants.q8.a" },
      { id: "b", textoKey: "exercises:science.plants.q8.b" },
      { id: "c", textoKey: "exercises:science.plants.q8.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },

  // ─── The human body: the senses ──────────────────────────────────────────
  {
    id: "sci-3-senses-001",
    materia: "ciencias",
    tema: "human_body.senses",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:science.senses.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:science.senses.q1.a" },
      { id: "b", textoKey: "exercises:science.senses.q1.b" },
      { id: "c", textoKey: "exercises:science.senses.q1.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "sci-3-senses-002",
    materia: "ciencias",
    tema: "human_body.senses",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:science.senses.q2.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:science.common.true" },
      { id: "false", textoKey: "exercises:science.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "sci-3-senses-003",
    materia: "ciencias",
    tema: "human_body.senses",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:science.senses.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:science.senses.q3.a" },
      { id: "b", textoKey: "exercises:science.senses.q3.b" },
      { id: "c", textoKey: "exercises:science.senses.q3.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "sci-3-senses-004",
    materia: "ciencias",
    tema: "human_body.senses",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:science.senses.q4.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:science.common.true" },
      { id: "false", textoKey: "exercises:science.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "sci-3-senses-005",
    materia: "ciencias",
    tema: "human_body.senses",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:science.senses.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:science.senses.q5.a" },
      { id: "b", textoKey: "exercises:science.senses.q5.b" },
      { id: "c", textoKey: "exercises:science.senses.q5.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "sci-3-senses-006",
    materia: "ciencias",
    tema: "human_body.senses",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:science.senses.q6.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:science.senses.q6.l1" },
      { id: "l2", textoKey: "exercises:science.senses.q6.l2" },
      { id: "l3", textoKey: "exercises:science.senses.q6.l3" },
      { id: "r1", textoKey: "exercises:science.senses.q6.r1" },
      { id: "r2", textoKey: "exercises:science.senses.q6.r2" },
      { id: "r3", textoKey: "exercises:science.senses.q6.r3" },
    ],
    respuestaCorrecta: ["l1:r3", "l2:r1", "l3:r2"],
    imprimible: true,
  },
  {
    id: "sci-3-senses-007",
    materia: "ciencias",
    tema: "human_body.senses",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:science.senses.q7.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:science.common.true" },
      { id: "false", textoKey: "exercises:science.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "sci-3-senses-008",
    materia: "ciencias",
    tema: "human_body.senses",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:science.senses.q8.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:science.senses.q8.a" },
      { id: "b", textoKey: "exercises:science.senses.q8.b" },
      { id: "c", textoKey: "exercises:science.senses.q8.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },

  // ─── The human body: health and nutrition ─────────────────────────────────
  {
    id: "sci-3-nutrition-001",
    materia: "ciencias",
    tema: "human_body.nutrition",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:science.nutrition.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:science.nutrition.q1.a" },
      { id: "b", textoKey: "exercises:science.nutrition.q1.b" },
      { id: "c", textoKey: "exercises:science.nutrition.q1.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "sci-3-nutrition-002",
    materia: "ciencias",
    tema: "human_body.nutrition",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:science.nutrition.q2.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:science.common.true" },
      { id: "false", textoKey: "exercises:science.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "sci-3-nutrition-003",
    materia: "ciencias",
    tema: "human_body.nutrition",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:science.nutrition.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:science.nutrition.q3.a" },
      { id: "b", textoKey: "exercises:science.nutrition.q3.b" },
      { id: "c", textoKey: "exercises:science.nutrition.q3.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "sci-3-nutrition-004",
    materia: "ciencias",
    tema: "human_body.nutrition",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:science.nutrition.q4.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:science.common.true" },
      { id: "false", textoKey: "exercises:science.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "sci-3-nutrition-005",
    materia: "ciencias",
    tema: "human_body.nutrition",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:science.nutrition.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:science.nutrition.q5.a" },
      { id: "b", textoKey: "exercises:science.nutrition.q5.b" },
      { id: "c", textoKey: "exercises:science.nutrition.q5.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "sci-3-nutrition-006",
    materia: "ciencias",
    tema: "human_body.nutrition",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:science.nutrition.q6.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:science.nutrition.q6.l1" },
      { id: "l2", textoKey: "exercises:science.nutrition.q6.l2" },
      { id: "l3", textoKey: "exercises:science.nutrition.q6.l3" },
      { id: "r1", textoKey: "exercises:science.nutrition.q6.r1" },
      { id: "r2", textoKey: "exercises:science.nutrition.q6.r2" },
      { id: "r3", textoKey: "exercises:science.nutrition.q6.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r3", "l3:r1"],
    imprimible: true,
  },
  {
    id: "sci-3-nutrition-007",
    materia: "ciencias",
    tema: "human_body.nutrition",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:science.nutrition.q7.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:science.common.true" },
      { id: "false", textoKey: "exercises:science.common.false" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "sci-3-nutrition-008",
    materia: "ciencias",
    tema: "human_body.nutrition",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:science.nutrition.q8.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:science.nutrition.q8.a" },
      { id: "b", textoKey: "exercises:science.nutrition.q8.b" },
      { id: "c", textoKey: "exercises:science.nutrition.q8.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },

  // ─── Matter and energy: states of matter ─────────────────────────────────
  {
    id: "sci-3-states-001",
    materia: "ciencias",
    tema: "matter_energy.states",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:science.states.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:science.states.q1.a" },
      { id: "b", textoKey: "exercises:science.states.q1.b" },
      { id: "c", textoKey: "exercises:science.states.q1.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "sci-3-states-002",
    materia: "ciencias",
    tema: "matter_energy.states",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:science.states.q2.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:science.states.q2.l1" },
      { id: "l2", textoKey: "exercises:science.states.q2.l2" },
      { id: "l3", textoKey: "exercises:science.states.q2.l3" },
      { id: "r1", textoKey: "exercises:science.states.q2.r1" },
      { id: "r2", textoKey: "exercises:science.states.q2.r2" },
      { id: "r3", textoKey: "exercises:science.states.q2.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r1", "l3:r3"],
    imprimible: true,
  },
  {
    id: "sci-3-states-003",
    materia: "ciencias",
    tema: "matter_energy.states",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:science.states.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:science.states.q3.a" },
      { id: "b", textoKey: "exercises:science.states.q3.b" },
      { id: "c", textoKey: "exercises:science.states.q3.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "sci-3-states-004",
    materia: "ciencias",
    tema: "matter_energy.states",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:science.states.q4.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:science.common.true" },
      { id: "false", textoKey: "exercises:science.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "sci-3-states-005",
    materia: "ciencias",
    tema: "matter_energy.states",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:science.states.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:science.states.q5.a" },
      { id: "b", textoKey: "exercises:science.states.q5.b" },
      { id: "c", textoKey: "exercises:science.states.q5.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "sci-3-states-006",
    materia: "ciencias",
    tema: "matter_energy.states",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:science.states.q6.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:science.common.true" },
      { id: "false", textoKey: "exercises:science.common.false" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "sci-3-states-007",
    materia: "ciencias",
    tema: "matter_energy.states",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:science.states.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:science.states.q7.a" },
      { id: "b", textoKey: "exercises:science.states.q7.b" },
      { id: "c", textoKey: "exercises:science.states.q7.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "sci-3-states-008",
    materia: "ciencias",
    tema: "matter_energy.states",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:science.states.q8.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:science.states.q8.l1" },
      { id: "l2", textoKey: "exercises:science.states.q8.l2" },
      { id: "l3", textoKey: "exercises:science.states.q8.l3" },
      { id: "r1", textoKey: "exercises:science.states.q8.r1" },
      { id: "r2", textoKey: "exercises:science.states.q8.r2" },
      { id: "r3", textoKey: "exercises:science.states.q8.r3" },
    ],
    respuestaCorrecta: ["l1:r3", "l2:r1", "l3:r2"],
    imprimible: true,
  },
];
