/*
 * Contenido de Introducción a 4º de Primaria.
 * 5 temas × 32 ejercicios = 160 ejercicios en total.
 * Sigue el idioma de la UI (las claves i18n viven en EN y ES).
 */
import type { EjercicioAny } from "../types";

const tf = (id: string, tema: string, q: string, ans: "true" | "false"): EjercicioAny => ({
  id, materia: "cuarto", tema, nivel: "3", tipo: "verdadero-falso",
  enunciadoKey: q,
  opciones: [
    { id: "true", textoKey: "quiz:answer.trueLabel" },
    { id: "false", textoKey: "quiz:answer.falseLabel" },
  ],
  respuestaCorrecta: ans,
  imprimible: true,
});

const mc = (id: string, tema: string, q: string, ans: "a" | "b" | "c", sec: string, n: string): EjercicioAny => ({
  id, materia: "cuarto", tema, nivel: "3", tipo: "opcion-multiple",
  enunciadoKey: q,
  opciones: [
    { id: "a", textoKey: `exercises:cuarto4.${sec}.${n}.a` },
    { id: "b", textoKey: `exercises:cuarto4.${sec}.${n}.b` },
    { id: "c", textoKey: `exercises:cuarto4.${sec}.${n}.c` },
  ],
  respuestaCorrecta: ans,
  imprimible: true,
});

export const cuarto: EjercicioAny[] = [
  // ─── Preview Matemáticas (q1-q32) ────────────────────────────────────────
  tf("c4-math-001","preview.math","exercises:cuarto4.math.q1.prompt","true"),
  tf("c4-math-002","preview.math","exercises:cuarto4.math.q2.prompt","true"),
  mc("c4-math-003","preview.math","exercises:cuarto4.math.q3.prompt","b","math","q3"),
  tf("c4-math-004","preview.math","exercises:cuarto4.math.q4.prompt","true"),
  mc("c4-math-005","preview.math","exercises:cuarto4.math.q5.prompt","c","math","q5"),
  tf("c4-math-006","preview.math","exercises:cuarto4.math.q6.prompt","true"),
  mc("c4-math-007","preview.math","exercises:cuarto4.math.q7.prompt","b","math","q7"),
  tf("c4-math-008","preview.math","exercises:cuarto4.math.q8.prompt","true"),
  mc("c4-math-009","preview.math","exercises:cuarto4.math.q9.prompt","c","math","q9"),
  tf("c4-math-010","preview.math","exercises:cuarto4.math.q10.prompt","true"),
  mc("c4-math-011","preview.math","exercises:cuarto4.math.q11.prompt","b","math","q11"),
  tf("c4-math-012","preview.math","exercises:cuarto4.math.q12.prompt","true"),
  mc("c4-math-013","preview.math","exercises:cuarto4.math.q13.prompt","c","math","q13"),
  tf("c4-math-014","preview.math","exercises:cuarto4.math.q14.prompt","true"),
  mc("c4-math-015","preview.math","exercises:cuarto4.math.q15.prompt","b","math","q15"),
  tf("c4-math-016","preview.math","exercises:cuarto4.math.q16.prompt","true"),
  mc("c4-math-017","preview.math","exercises:cuarto4.math.q17.prompt","b","math","q17"),
  tf("c4-math-018","preview.math","exercises:cuarto4.math.q18.prompt","true"),
  mc("c4-math-019","preview.math","exercises:cuarto4.math.q19.prompt","b","math","q19"),
  tf("c4-math-020","preview.math","exercises:cuarto4.math.q20.prompt","true"),
  mc("c4-math-021","preview.math","exercises:cuarto4.math.q21.prompt","b","math","q21"),
  tf("c4-math-022","preview.math","exercises:cuarto4.math.q22.prompt","true"),
  mc("c4-math-023","preview.math","exercises:cuarto4.math.q23.prompt","b","math","q23"),
  tf("c4-math-024","preview.math","exercises:cuarto4.math.q24.prompt","true"),
  mc("c4-math-025","preview.math","exercises:cuarto4.math.q25.prompt","b","math","q25"),
  tf("c4-math-026","preview.math","exercises:cuarto4.math.q26.prompt","true"),
  mc("c4-math-027","preview.math","exercises:cuarto4.math.q27.prompt","b","math","q27"),
  tf("c4-math-028","preview.math","exercises:cuarto4.math.q28.prompt","true"),
  mc("c4-math-029","preview.math","exercises:cuarto4.math.q29.prompt","b","math","q29"),
  tf("c4-math-030","preview.math","exercises:cuarto4.math.q30.prompt","true"),
  mc("c4-math-031","preview.math","exercises:cuarto4.math.q31.prompt","c","math","q31"),
  tf("c4-math-032","preview.math","exercises:cuarto4.math.q32.prompt","false"),

  // ─── Preview Lengua (q1-q32) ──────────────────────────────────────────────
  tf("c4-esp-001","preview.spanish","exercises:cuarto4.spanish.q1.prompt","true"),
  tf("c4-esp-002","preview.spanish","exercises:cuarto4.spanish.q2.prompt","true"),
  mc("c4-esp-003","preview.spanish","exercises:cuarto4.spanish.q3.prompt","c","spanish","q3"),
  tf("c4-esp-004","preview.spanish","exercises:cuarto4.spanish.q4.prompt","true"),
  mc("c4-esp-005","preview.spanish","exercises:cuarto4.spanish.q5.prompt","b","spanish","q5"),
  tf("c4-esp-006","preview.spanish","exercises:cuarto4.spanish.q6.prompt","true"),
  mc("c4-esp-007","preview.spanish","exercises:cuarto4.spanish.q7.prompt","b","spanish","q7"),
  tf("c4-esp-008","preview.spanish","exercises:cuarto4.spanish.q8.prompt","false"),
  mc("c4-esp-009","preview.spanish","exercises:cuarto4.spanish.q9.prompt","b","spanish","q9"),
  tf("c4-esp-010","preview.spanish","exercises:cuarto4.spanish.q10.prompt","true"),
  mc("c4-esp-011","preview.spanish","exercises:cuarto4.spanish.q11.prompt","b","spanish","q11"),
  tf("c4-esp-012","preview.spanish","exercises:cuarto4.spanish.q12.prompt","true"),
  mc("c4-esp-013","preview.spanish","exercises:cuarto4.spanish.q13.prompt","b","spanish","q13"),
  tf("c4-esp-014","preview.spanish","exercises:cuarto4.spanish.q14.prompt","false"),
  mc("c4-esp-015","preview.spanish","exercises:cuarto4.spanish.q15.prompt","b","spanish","q15"),
  tf("c4-esp-016","preview.spanish","exercises:cuarto4.spanish.q16.prompt","true"),
  mc("c4-esp-017","preview.spanish","exercises:cuarto4.spanish.q17.prompt","b","spanish","q17"),
  tf("c4-esp-018","preview.spanish","exercises:cuarto4.spanish.q18.prompt","true"),
  mc("c4-esp-019","preview.spanish","exercises:cuarto4.spanish.q19.prompt","c","spanish","q19"),
  tf("c4-esp-020","preview.spanish","exercises:cuarto4.spanish.q20.prompt","true"),
  mc("c4-esp-021","preview.spanish","exercises:cuarto4.spanish.q21.prompt","a","spanish","q21"),
  tf("c4-esp-022","preview.spanish","exercises:cuarto4.spanish.q22.prompt","true"),
  mc("c4-esp-023","preview.spanish","exercises:cuarto4.spanish.q23.prompt","c","spanish","q23"),
  tf("c4-esp-024","preview.spanish","exercises:cuarto4.spanish.q24.prompt","false"),
  mc("c4-esp-025","preview.spanish","exercises:cuarto4.spanish.q25.prompt","b","spanish","q25"),
  tf("c4-esp-026","preview.spanish","exercises:cuarto4.spanish.q26.prompt","true"),
  mc("c4-esp-027","preview.spanish","exercises:cuarto4.spanish.q27.prompt","b","spanish","q27"),
  tf("c4-esp-028","preview.spanish","exercises:cuarto4.spanish.q28.prompt","true"),
  mc("c4-esp-029","preview.spanish","exercises:cuarto4.spanish.q29.prompt","b","spanish","q29"),
  tf("c4-esp-030","preview.spanish","exercises:cuarto4.spanish.q30.prompt","true"),
  mc("c4-esp-031","preview.spanish","exercises:cuarto4.spanish.q31.prompt","c","spanish","q31"),
  tf("c4-esp-032","preview.spanish","exercises:cuarto4.spanish.q32.prompt","true"),

  // ─── Preview Ciencias (q1-q32) ────────────────────────────────────────────
  tf("c4-sci-001","preview.science","exercises:cuarto4.science.q1.prompt","true"),
  tf("c4-sci-002","preview.science","exercises:cuarto4.science.q2.prompt","true"),
  mc("c4-sci-003","preview.science","exercises:cuarto4.science.q3.prompt","c","science","q3"),
  tf("c4-sci-004","preview.science","exercises:cuarto4.science.q4.prompt","true"),
  mc("c4-sci-005","preview.science","exercises:cuarto4.science.q5.prompt","b","science","q5"),
  tf("c4-sci-006","preview.science","exercises:cuarto4.science.q6.prompt","true"),
  mc("c4-sci-007","preview.science","exercises:cuarto4.science.q7.prompt","a","science","q7"),
  tf("c4-sci-008","preview.science","exercises:cuarto4.science.q8.prompt","true"),
  mc("c4-sci-009","preview.science","exercises:cuarto4.science.q9.prompt","b","science","q9"),
  tf("c4-sci-010","preview.science","exercises:cuarto4.science.q10.prompt","true"),
  mc("c4-sci-011","preview.science","exercises:cuarto4.science.q11.prompt","c","science","q11"),
  tf("c4-sci-012","preview.science","exercises:cuarto4.science.q12.prompt","true"),
  mc("c4-sci-013","preview.science","exercises:cuarto4.science.q13.prompt","b","science","q13"),
  tf("c4-sci-014","preview.science","exercises:cuarto4.science.q14.prompt","true"),
  mc("c4-sci-015","preview.science","exercises:cuarto4.science.q15.prompt","b","science","q15"),
  tf("c4-sci-016","preview.science","exercises:cuarto4.science.q16.prompt","true"),
  mc("c4-sci-017","preview.science","exercises:cuarto4.science.q17.prompt","b","science","q17"),
  tf("c4-sci-018","preview.science","exercises:cuarto4.science.q18.prompt","true"),
  mc("c4-sci-019","preview.science","exercises:cuarto4.science.q19.prompt","c","science","q19"),
  tf("c4-sci-020","preview.science","exercises:cuarto4.science.q20.prompt","true"),
  mc("c4-sci-021","preview.science","exercises:cuarto4.science.q21.prompt","b","science","q21"),
  tf("c4-sci-022","preview.science","exercises:cuarto4.science.q22.prompt","true"),
  mc("c4-sci-023","preview.science","exercises:cuarto4.science.q23.prompt","c","science","q23"),
  tf("c4-sci-024","preview.science","exercises:cuarto4.science.q24.prompt","true"),
  mc("c4-sci-025","preview.science","exercises:cuarto4.science.q25.prompt","c","science","q25"),
  tf("c4-sci-026","preview.science","exercises:cuarto4.science.q26.prompt","true"),
  mc("c4-sci-027","preview.science","exercises:cuarto4.science.q27.prompt","a","science","q27"),
  tf("c4-sci-028","preview.science","exercises:cuarto4.science.q28.prompt","true"),
  mc("c4-sci-029","preview.science","exercises:cuarto4.science.q29.prompt","c","science","q29"),
  tf("c4-sci-030","preview.science","exercises:cuarto4.science.q30.prompt","true"),
  mc("c4-sci-031","preview.science","exercises:cuarto4.science.q31.prompt","b","science","q31"),
  tf("c4-sci-032","preview.science","exercises:cuarto4.science.q32.prompt","true"),

  // ─── Preview Sociales (q1-q32) ────────────────────────────────────────────
  tf("c4-soc-001","preview.social","exercises:cuarto4.social.q1.prompt","false"),
  tf("c4-soc-002","preview.social","exercises:cuarto4.social.q2.prompt","true"),
  mc("c4-soc-003","preview.social","exercises:cuarto4.social.q3.prompt","c","social","q3"),
  tf("c4-soc-004","preview.social","exercises:cuarto4.social.q4.prompt","true"),
  mc("c4-soc-005","preview.social","exercises:cuarto4.social.q5.prompt","b","social","q5"),
  tf("c4-soc-006","preview.social","exercises:cuarto4.social.q6.prompt","true"),
  mc("c4-soc-007","preview.social","exercises:cuarto4.social.q7.prompt","c","social","q7"),
  tf("c4-soc-008","preview.social","exercises:cuarto4.social.q8.prompt","true"),
  mc("c4-soc-009","preview.social","exercises:cuarto4.social.q9.prompt","b","social","q9"),
  tf("c4-soc-010","preview.social","exercises:cuarto4.social.q10.prompt","true"),
  mc("c4-soc-011","preview.social","exercises:cuarto4.social.q11.prompt","b","social","q11"),
  tf("c4-soc-012","preview.social","exercises:cuarto4.social.q12.prompt","true"),
  mc("c4-soc-013","preview.social","exercises:cuarto4.social.q13.prompt","a","social","q13"),
  tf("c4-soc-014","preview.social","exercises:cuarto4.social.q14.prompt","true"),
  mc("c4-soc-015","preview.social","exercises:cuarto4.social.q15.prompt","c","social","q15"),
  tf("c4-soc-016","preview.social","exercises:cuarto4.social.q16.prompt","true"),
  mc("c4-soc-017","preview.social","exercises:cuarto4.social.q17.prompt","c","social","q17"),
  tf("c4-soc-018","preview.social","exercises:cuarto4.social.q18.prompt","true"),
  mc("c4-soc-019","preview.social","exercises:cuarto4.social.q19.prompt","b","social","q19"),
  tf("c4-soc-020","preview.social","exercises:cuarto4.social.q20.prompt","true"),
  mc("c4-soc-021","preview.social","exercises:cuarto4.social.q21.prompt","b","social","q21"),
  tf("c4-soc-022","preview.social","exercises:cuarto4.social.q22.prompt","true"),
  mc("c4-soc-023","preview.social","exercises:cuarto4.social.q23.prompt","b","social","q23"),
  tf("c4-soc-024","preview.social","exercises:cuarto4.social.q24.prompt","true"),
  mc("c4-soc-025","preview.social","exercises:cuarto4.social.q25.prompt","c","social","q25"),
  tf("c4-soc-026","preview.social","exercises:cuarto4.social.q26.prompt","true"),
  mc("c4-soc-027","preview.social","exercises:cuarto4.social.q27.prompt","b","social","q27"),
  tf("c4-soc-028","preview.social","exercises:cuarto4.social.q28.prompt","true"),
  mc("c4-soc-029","preview.social","exercises:cuarto4.social.q29.prompt","b","social","q29"),
  tf("c4-soc-030","preview.social","exercises:cuarto4.social.q30.prompt","true"),
  mc("c4-soc-031","preview.social","exercises:cuarto4.social.q31.prompt","b","social","q31"),
  tf("c4-soc-032","preview.social","exercises:cuarto4.social.q32.prompt","true"),

  // ─── Preview Inglés (q1-q32) ──────────────────────────────────────────────
  tf("c4-eng-001","preview.english","exercises:cuarto4.english.q1.prompt","true"),
  tf("c4-eng-002","preview.english","exercises:cuarto4.english.q2.prompt","false"),
  mc("c4-eng-003","preview.english","exercises:cuarto4.english.q3.prompt","b","english","q3"),
  tf("c4-eng-004","preview.english","exercises:cuarto4.english.q4.prompt","true"),
  mc("c4-eng-005","preview.english","exercises:cuarto4.english.q5.prompt","a","english","q5"),
  tf("c4-eng-006","preview.english","exercises:cuarto4.english.q6.prompt","false"),
  mc("c4-eng-007","preview.english","exercises:cuarto4.english.q7.prompt","c","english","q7"),
  tf("c4-eng-008","preview.english","exercises:cuarto4.english.q8.prompt","true"),
  mc("c4-eng-009","preview.english","exercises:cuarto4.english.q9.prompt","b","english","q9"),
  tf("c4-eng-010","preview.english","exercises:cuarto4.english.q10.prompt","true"),
  mc("c4-eng-011","preview.english","exercises:cuarto4.english.q11.prompt","a","english","q11"),
  tf("c4-eng-012","preview.english","exercises:cuarto4.english.q12.prompt","true"),
  mc("c4-eng-013","preview.english","exercises:cuarto4.english.q13.prompt","b","english","q13"),
  tf("c4-eng-014","preview.english","exercises:cuarto4.english.q14.prompt","true"),
  mc("c4-eng-015","preview.english","exercises:cuarto4.english.q15.prompt","b","english","q15"),
  tf("c4-eng-016","preview.english","exercises:cuarto4.english.q16.prompt","true"),
  mc("c4-eng-017","preview.english","exercises:cuarto4.english.q17.prompt","c","english","q17"),
  tf("c4-eng-018","preview.english","exercises:cuarto4.english.q18.prompt","true"),
  mc("c4-eng-019","preview.english","exercises:cuarto4.english.q19.prompt","b","english","q19"),
  tf("c4-eng-020","preview.english","exercises:cuarto4.english.q20.prompt","false"),
  mc("c4-eng-021","preview.english","exercises:cuarto4.english.q21.prompt","b","english","q21"),
  tf("c4-eng-022","preview.english","exercises:cuarto4.english.q22.prompt","true"),
  mc("c4-eng-023","preview.english","exercises:cuarto4.english.q23.prompt","b","english","q23"),
  tf("c4-eng-024","preview.english","exercises:cuarto4.english.q24.prompt","true"),
  mc("c4-eng-025","preview.english","exercises:cuarto4.english.q25.prompt","c","english","q25"),
  tf("c4-eng-026","preview.english","exercises:cuarto4.english.q26.prompt","true"),
  mc("c4-eng-027","preview.english","exercises:cuarto4.english.q27.prompt","b","english","q27"),
  tf("c4-eng-028","preview.english","exercises:cuarto4.english.q28.prompt","true"),
  mc("c4-eng-029","preview.english","exercises:cuarto4.english.q29.prompt","b","english","q29"),
  tf("c4-eng-030","preview.english","exercises:cuarto4.english.q30.prompt","true"),
  mc("c4-eng-031","preview.english","exercises:cuarto4.english.q31.prompt","b","english","q31"),
  tf("c4-eng-032","preview.english","exercises:cuarto4.english.q32.prompt","true"),


  // ─── Preview Matemáticas (q33+) ─────────────────────────────────────────
  tf("c4-math-033","preview.math","exercises:cuarto4.math.q33.prompt","true"),
  mc("c4-math-034","preview.math","exercises:cuarto4.math.q34.prompt","a","math","q34"),
  tf("c4-math-035","preview.math","exercises:cuarto4.math.q35.prompt","true"),
  mc("c4-math-036","preview.math","exercises:cuarto4.math.q36.prompt","a","math","q36"),
  tf("c4-math-037","preview.math","exercises:cuarto4.math.q37.prompt","true"),
  mc("c4-math-038","preview.math","exercises:cuarto4.math.q38.prompt","c","math","q38"),
  tf("c4-math-039","preview.math","exercises:cuarto4.math.q39.prompt","true"),
  mc("c4-math-040","preview.math","exercises:cuarto4.math.q40.prompt","c","math","q40"),
  tf("c4-math-041","preview.math","exercises:cuarto4.math.q41.prompt","true"),
  mc("c4-math-042","preview.math","exercises:cuarto4.math.q42.prompt","b","math","q42"),
  tf("c4-math-043","preview.math","exercises:cuarto4.math.q43.prompt","true"),
  mc("c4-math-044","preview.math","exercises:cuarto4.math.q44.prompt","a","math","q44"),
  tf("c4-math-045","preview.math","exercises:cuarto4.math.q45.prompt","true"),
  mc("c4-math-046","preview.math","exercises:cuarto4.math.q46.prompt","b","math","q46"),
  tf("c4-math-047","preview.math","exercises:cuarto4.math.q47.prompt","true"),
  mc("c4-math-048","preview.math","exercises:cuarto4.math.q48.prompt","c","math","q48"),
  tf("c4-math-049","preview.math","exercises:cuarto4.math.q49.prompt","true"),
  mc("c4-math-050","preview.math","exercises:cuarto4.math.q50.prompt","b","math","q50"),
  tf("c4-math-051","preview.math","exercises:cuarto4.math.q51.prompt","true"),
  mc("c4-math-052","preview.math","exercises:cuarto4.math.q52.prompt","b","math","q52"),

  // ─── Preview Lengua (q33+) ───────────────────────────────────────────────
  tf("c4-esp-033","preview.spanish","exercises:cuarto4.spanish.q33.prompt","true"),
  mc("c4-esp-034","preview.spanish","exercises:cuarto4.spanish.q34.prompt","b","spanish","q34"),
  tf("c4-esp-035","preview.spanish","exercises:cuarto4.spanish.q35.prompt","true"),
  mc("c4-esp-036","preview.spanish","exercises:cuarto4.spanish.q36.prompt","b","spanish","q36"),
  tf("c4-esp-037","preview.spanish","exercises:cuarto4.spanish.q37.prompt","true"),
  mc("c4-esp-038","preview.spanish","exercises:cuarto4.spanish.q38.prompt","b","spanish","q38"),
  tf("c4-esp-039","preview.spanish","exercises:cuarto4.spanish.q39.prompt","true"),
  mc("c4-esp-040","preview.spanish","exercises:cuarto4.spanish.q40.prompt","b","spanish","q40"),
  tf("c4-esp-041","preview.spanish","exercises:cuarto4.spanish.q41.prompt","true"),
  mc("c4-esp-042","preview.spanish","exercises:cuarto4.spanish.q42.prompt","c","spanish","q42"),
  tf("c4-esp-043","preview.spanish","exercises:cuarto4.spanish.q43.prompt","true"),
  mc("c4-esp-044","preview.spanish","exercises:cuarto4.spanish.q44.prompt","b","spanish","q44"),
  tf("c4-esp-045","preview.spanish","exercises:cuarto4.spanish.q45.prompt","true"),
  mc("c4-esp-046","preview.spanish","exercises:cuarto4.spanish.q46.prompt","a","spanish","q46"),
  tf("c4-esp-047","preview.spanish","exercises:cuarto4.spanish.q47.prompt","true"),
  mc("c4-esp-048","preview.spanish","exercises:cuarto4.spanish.q48.prompt","b","spanish","q48"),
  tf("c4-esp-049","preview.spanish","exercises:cuarto4.spanish.q49.prompt","true"),
  mc("c4-esp-050","preview.spanish","exercises:cuarto4.spanish.q50.prompt","b","spanish","q50"),
  tf("c4-esp-051","preview.spanish","exercises:cuarto4.spanish.q51.prompt","true"),

  // ─── Preview Ciencias (q33+) ─────────────────────────────────────────────
  tf("c4-sci-033","preview.science","exercises:cuarto4.science.q33.prompt","true"),
  mc("c4-sci-034","preview.science","exercises:cuarto4.science.q34.prompt","b","science","q34"),
  tf("c4-sci-035","preview.science","exercises:cuarto4.science.q35.prompt","true"),
  mc("c4-sci-036","preview.science","exercises:cuarto4.science.q36.prompt","c","science","q36"),
  tf("c4-sci-037","preview.science","exercises:cuarto4.science.q37.prompt","true"),
  mc("c4-sci-038","preview.science","exercises:cuarto4.science.q38.prompt","b","science","q38"),
  tf("c4-sci-039","preview.science","exercises:cuarto4.science.q39.prompt","true"),
  mc("c4-sci-040","preview.science","exercises:cuarto4.science.q40.prompt","c","science","q40"),
  tf("c4-sci-041","preview.science","exercises:cuarto4.science.q41.prompt","true"),
  mc("c4-sci-042","preview.science","exercises:cuarto4.science.q42.prompt","b","science","q42"),
  tf("c4-sci-043","preview.science","exercises:cuarto4.science.q43.prompt","true"),
  mc("c4-sci-044","preview.science","exercises:cuarto4.science.q44.prompt","c","science","q44"),
  tf("c4-sci-045","preview.science","exercises:cuarto4.science.q45.prompt","true"),
  mc("c4-sci-046","preview.science","exercises:cuarto4.science.q46.prompt","c","science","q46"),
  tf("c4-sci-047","preview.science","exercises:cuarto4.science.q47.prompt","true"),
  mc("c4-sci-048","preview.science","exercises:cuarto4.science.q48.prompt","a","science","q48"),
  tf("c4-sci-049","preview.science","exercises:cuarto4.science.q49.prompt","true"),
  mc("c4-sci-050","preview.science","exercises:cuarto4.science.q50.prompt","c","science","q50"),
  tf("c4-sci-051","preview.science","exercises:cuarto4.science.q51.prompt","true"),

  // ─── Preview Sociales (q33+) ─────────────────────────────────────────────
  tf("c4-soc-033","preview.social","exercises:cuarto4.social.q33.prompt","true"),
  mc("c4-soc-034","preview.social","exercises:cuarto4.social.q34.prompt","b","social","q34"),
  tf("c4-soc-035","preview.social","exercises:cuarto4.social.q35.prompt","true"),
  mc("c4-soc-036","preview.social","exercises:cuarto4.social.q36.prompt","b","social","q36"),
  tf("c4-soc-037","preview.social","exercises:cuarto4.social.q37.prompt","true"),
  mc("c4-soc-038","preview.social","exercises:cuarto4.social.q38.prompt","c","social","q38"),
  tf("c4-soc-039","preview.social","exercises:cuarto4.social.q39.prompt","true"),
  mc("c4-soc-040","preview.social","exercises:cuarto4.social.q40.prompt","b","social","q40"),
  tf("c4-soc-041","preview.social","exercises:cuarto4.social.q41.prompt","true"),
  mc("c4-soc-042","preview.social","exercises:cuarto4.social.q42.prompt","b","social","q42"),
  tf("c4-soc-043","preview.social","exercises:cuarto4.social.q43.prompt","true"),
  mc("c4-soc-044","preview.social","exercises:cuarto4.social.q44.prompt","b","social","q44"),
  tf("c4-soc-045","preview.social","exercises:cuarto4.social.q45.prompt","true"),
  mc("c4-soc-046","preview.social","exercises:cuarto4.social.q46.prompt","b","social","q46"),
  tf("c4-soc-047","preview.social","exercises:cuarto4.social.q47.prompt","true"),
  mc("c4-soc-048","preview.social","exercises:cuarto4.social.q48.prompt","b","social","q48"),
  tf("c4-soc-049","preview.social","exercises:cuarto4.social.q49.prompt","true"),
  mc("c4-soc-050","preview.social","exercises:cuarto4.social.q50.prompt","c","social","q50"),
  tf("c4-soc-051","preview.social","exercises:cuarto4.social.q51.prompt","true"),

  // ─── Preview Inglés (q33+) ───────────────────────────────────────────────
  tf("c4-eng-033","preview.english","exercises:cuarto4.english.q33.prompt","true"),
  mc("c4-eng-034","preview.english","exercises:cuarto4.english.q34.prompt","b","english","q34"),
  tf("c4-eng-035","preview.english","exercises:cuarto4.english.q35.prompt","true"),
  mc("c4-eng-036","preview.english","exercises:cuarto4.english.q36.prompt","b","english","q36"),
  tf("c4-eng-037","preview.english","exercises:cuarto4.english.q37.prompt","true"),
  mc("c4-eng-038","preview.english","exercises:cuarto4.english.q38.prompt","b","english","q38"),
  tf("c4-eng-039","preview.english","exercises:cuarto4.english.q39.prompt","true"),
  mc("c4-eng-040","preview.english","exercises:cuarto4.english.q40.prompt","b","english","q40"),
  tf("c4-eng-041","preview.english","exercises:cuarto4.english.q41.prompt","true"),
  mc("c4-eng-042","preview.english","exercises:cuarto4.english.q42.prompt","a","english","q42"),
  tf("c4-eng-043","preview.english","exercises:cuarto4.english.q43.prompt","true"),
  mc("c4-eng-044","preview.english","exercises:cuarto4.english.q44.prompt","b","english","q44"),
  tf("c4-eng-045","preview.english","exercises:cuarto4.english.q45.prompt","true"),
  mc("c4-eng-046","preview.english","exercises:cuarto4.english.q46.prompt","b","english","q46"),
  tf("c4-eng-047","preview.english","exercises:cuarto4.english.q47.prompt","true"),
  mc("c4-eng-048","preview.english","exercises:cuarto4.english.q48.prompt","c","english","q48"),
  tf("c4-eng-049","preview.english","exercises:cuarto4.english.q49.prompt","true"),
  mc("c4-eng-050","preview.english","exercises:cuarto4.english.q50.prompt","c","english","q50"),
  tf("c4-eng-051","preview.english","exercises:cuarto4.english.q51.prompt","true"),

];
