/*
 * English subject content — naturally in English. Like Spanish and Natural
 * Science, its content does NOT follow the UI language selector. Its i18n keys
 * only exist in EN. Original content.
 */
import type { EjercicioAny } from "../types";

const tfE = (id: string, tema: string, sec: string, n: string, ans: "true" | "false"): EjercicioAny => ({
  id, materia: "ingles", tema, nivel: "3", tipo: "verdadero-falso",
  enunciadoKey: `exercises:english.${sec}.${n}.prompt`,
  opciones: [
    { id: "true",  textoKey: "exercises:english.common.true" },
    { id: "false", textoKey: "exercises:english.common.false" },
  ],
  respuestaCorrecta: ans,
  imprimible: true,
});
const mcE = (id: string, tema: string, sec: string, n: string, ans: "a" | "b" | "c"): EjercicioAny => ({
  id, materia: "ingles", tema, nivel: "3", tipo: "opcion-multiple",
  enunciadoKey: `exercises:english.${sec}.${n}.prompt`,
  opciones: [
    { id: "a", textoKey: `exercises:english.${sec}.${n}.a` },
    { id: "b", textoKey: `exercises:english.${sec}.${n}.b` },
    { id: "c", textoKey: `exercises:english.${sec}.${n}.c` },
  ],
  respuestaCorrecta: ans,
  imprimible: true,
});
const matchE = (id: string, tema: string, sec: string, n: string, pairs: string[]): EjercicioAny => ({
  id, materia: "ingles", tema, nivel: "3", tipo: "emparejar",
  enunciadoKey: `exercises:english.${sec}.${n}.prompt`,
  opciones: [
    { id: "l1", textoKey: `exercises:english.${sec}.${n}.l1` },
    { id: "l2", textoKey: `exercises:english.${sec}.${n}.l2` },
    { id: "l3", textoKey: `exercises:english.${sec}.${n}.l3` },
    { id: "r1", textoKey: `exercises:english.${sec}.${n}.r1` },
    { id: "r2", textoKey: `exercises:english.${sec}.${n}.r2` },
    { id: "r3", textoKey: `exercises:english.${sec}.${n}.r3` },
  ],
  respuestaCorrecta: pairs,
  imprimible: true,
});

export const ingles: EjercicioAny[] = [

  // ─── Vocabulary: colours and shapes ──────────────────────────────────────
  {
    id: "eng-3-colors-001",
    materia: "ingles",
    tema: "en_vocabulary.colors_shapes",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.colors.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.colors.q1.a" },
      { id: "b", textoKey: "exercises:english.colors.q1.b" },
      { id: "c", textoKey: "exercises:english.colors.q1.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "eng-3-colors-002",
    materia: "ingles",
    tema: "en_vocabulary.colors_shapes",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:english.colors.q2.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:english.colors.q2.l1" },
      { id: "l2", textoKey: "exercises:english.colors.q2.l2" },
      { id: "l3", textoKey: "exercises:english.colors.q2.l3" },
      { id: "r1", textoKey: "exercises:english.colors.q2.r1" },
      { id: "r2", textoKey: "exercises:english.colors.q2.r2" },
      { id: "r3", textoKey: "exercises:english.colors.q2.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r1", "l3:r3"],
    imprimible: true,
  },
  {
    id: "eng-3-colors-003",
    materia: "ingles",
    tema: "en_vocabulary.colors_shapes",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.colors.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.colors.q3.a" },
      { id: "b", textoKey: "exercises:english.colors.q3.b" },
      { id: "c", textoKey: "exercises:english.colors.q3.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "eng-3-colors-004",
    materia: "ingles",
    tema: "en_vocabulary.colors_shapes",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.colors.q4.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "eng-3-colors-005",
    materia: "ingles",
    tema: "en_vocabulary.colors_shapes",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.colors.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.colors.q5.a" },
      { id: "b", textoKey: "exercises:english.colors.q5.b" },
      { id: "c", textoKey: "exercises:english.colors.q5.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-colors-006",
    materia: "ingles",
    tema: "en_vocabulary.colors_shapes",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.colors.q6.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "eng-3-colors-007",
    materia: "ingles",
    tema: "en_vocabulary.colors_shapes",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.colors.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.colors.q7.a" },
      { id: "b", textoKey: "exercises:english.colors.q7.b" },
      { id: "c", textoKey: "exercises:english.colors.q7.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-colors-008",
    materia: "ingles",
    tema: "en_vocabulary.colors_shapes",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:english.colors.q8.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:english.colors.q8.l1" },
      { id: "l2", textoKey: "exercises:english.colors.q8.l2" },
      { id: "l3", textoKey: "exercises:english.colors.q8.l3" },
      { id: "r1", textoKey: "exercises:english.colors.q8.r1" },
      { id: "r2", textoKey: "exercises:english.colors.q8.r2" },
      { id: "r3", textoKey: "exercises:english.colors.q8.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r3", "l3:r1"],
    imprimible: true,
  },

  // ─── Vocabulary: animals ──────────────────────────────────────────────────
  {
    id: "eng-3-animals-001",
    materia: "ingles",
    tema: "en_vocabulary.animals",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.animals.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.animals.q1.a" },
      { id: "b", textoKey: "exercises:english.animals.q1.b" },
      { id: "c", textoKey: "exercises:english.animals.q1.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "eng-3-animals-002",
    materia: "ingles",
    tema: "en_vocabulary.animals",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.animals.q2.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "eng-3-animals-003",
    materia: "ingles",
    tema: "en_vocabulary.animals",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.animals.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.animals.q3.a" },
      { id: "b", textoKey: "exercises:english.animals.q3.b" },
      { id: "c", textoKey: "exercises:english.animals.q3.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "eng-3-animals-004",
    materia: "ingles",
    tema: "en_vocabulary.animals",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.animals.q4.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "eng-3-animals-005",
    materia: "ingles",
    tema: "en_vocabulary.animals",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.animals.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.animals.q5.a" },
      { id: "b", textoKey: "exercises:english.animals.q5.b" },
      { id: "c", textoKey: "exercises:english.animals.q5.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-animals-006",
    materia: "ingles",
    tema: "en_vocabulary.animals",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.animals.q6.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "eng-3-animals-007",
    materia: "ingles",
    tema: "en_vocabulary.animals",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:english.animals.q7.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:english.animals.q7.l1" },
      { id: "l2", textoKey: "exercises:english.animals.q7.l2" },
      { id: "l3", textoKey: "exercises:english.animals.q7.l3" },
      { id: "r1", textoKey: "exercises:english.animals.q7.r1" },
      { id: "r2", textoKey: "exercises:english.animals.q7.r2" },
      { id: "r3", textoKey: "exercises:english.animals.q7.r3" },
    ],
    respuestaCorrecta: ["l1:r3", "l2:r1", "l3:r2"],
    imprimible: true,
  },
  {
    id: "eng-3-animals-008",
    materia: "ingles",
    tema: "en_vocabulary.animals",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.animals.q8.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.animals.q8.a" },
      { id: "b", textoKey: "exercises:english.animals.q8.b" },
      { id: "c", textoKey: "exercises:english.animals.q8.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },

  // ─── Basics: greetings and introductions ──────────────────────────────────
  {
    id: "eng-3-greet-001",
    materia: "ingles",
    tema: "en_basics.greetings",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.greetings.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.greetings.q1.a" },
      { id: "b", textoKey: "exercises:english.greetings.q1.b" },
      { id: "c", textoKey: "exercises:english.greetings.q1.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-greet-002",
    materia: "ingles",
    tema: "en_basics.greetings",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.greetings.q2.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.greetings.q2.a" },
      { id: "b", textoKey: "exercises:english.greetings.q2.b" },
      { id: "c", textoKey: "exercises:english.greetings.q2.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "eng-3-greet-003",
    materia: "ingles",
    tema: "en_basics.greetings",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.greetings.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.greetings.q3.a" },
      { id: "b", textoKey: "exercises:english.greetings.q3.b" },
      { id: "c", textoKey: "exercises:english.greetings.q3.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-greet-004",
    materia: "ingles",
    tema: "en_basics.greetings",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.greetings.q4.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "eng-3-greet-005",
    materia: "ingles",
    tema: "en_basics.greetings",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.greetings.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.greetings.q5.a" },
      { id: "b", textoKey: "exercises:english.greetings.q5.b" },
      { id: "c", textoKey: "exercises:english.greetings.q5.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-greet-006",
    materia: "ingles",
    tema: "en_basics.greetings",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.greetings.q6.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "eng-3-greet-007",
    materia: "ingles",
    tema: "en_basics.greetings",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.greetings.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.greetings.q7.a" },
      { id: "b", textoKey: "exercises:english.greetings.q7.b" },
      { id: "c", textoKey: "exercises:english.greetings.q7.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "eng-3-greet-008",
    materia: "ingles",
    tema: "en_basics.greetings",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:english.greetings.q8.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:english.greetings.q8.l1" },
      { id: "l2", textoKey: "exercises:english.greetings.q8.l2" },
      { id: "l3", textoKey: "exercises:english.greetings.q8.l3" },
      { id: "r1", textoKey: "exercises:english.greetings.q8.r1" },
      { id: "r2", textoKey: "exercises:english.greetings.q8.r2" },
      { id: "r3", textoKey: "exercises:english.greetings.q8.r3" },
    ],
    respuestaCorrecta: ["l1:r3", "l2:r1", "l3:r2"],
    imprimible: true,
  },

  // ─── Vocabulary: numbers ──────────────────────────────────────────────────
  {
    id: "eng-3-numbers-001",
    materia: "ingles",
    tema: "en_vocabulary.numbers",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.numbers.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.numbers.q1.a" },
      { id: "b", textoKey: "exercises:english.numbers.q1.b" },
      { id: "c", textoKey: "exercises:english.numbers.q1.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-numbers-002",
    materia: "ingles",
    tema: "en_vocabulary.numbers",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.numbers.q2.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "eng-3-numbers-003",
    materia: "ingles",
    tema: "en_vocabulary.numbers",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.numbers.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.numbers.q3.a" },
      { id: "b", textoKey: "exercises:english.numbers.q3.b" },
      { id: "c", textoKey: "exercises:english.numbers.q3.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-numbers-004",
    materia: "ingles",
    tema: "en_vocabulary.numbers",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.numbers.q4.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "eng-3-numbers-005",
    materia: "ingles",
    tema: "en_vocabulary.numbers",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.numbers.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.numbers.q5.a" },
      { id: "b", textoKey: "exercises:english.numbers.q5.b" },
      { id: "c", textoKey: "exercises:english.numbers.q5.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "eng-3-numbers-006",
    materia: "ingles",
    tema: "en_vocabulary.numbers",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:english.numbers.q6.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:english.numbers.q6.l1" },
      { id: "l2", textoKey: "exercises:english.numbers.q6.l2" },
      { id: "l3", textoKey: "exercises:english.numbers.q6.l3" },
      { id: "r1", textoKey: "exercises:english.numbers.q6.r1" },
      { id: "r2", textoKey: "exercises:english.numbers.q6.r2" },
      { id: "r3", textoKey: "exercises:english.numbers.q6.r3" },
    ],
    respuestaCorrecta: ["l1:r3", "l2:r1", "l3:r2"],
    imprimible: true,
  },
  {
    id: "eng-3-numbers-007",
    materia: "ingles",
    tema: "en_vocabulary.numbers",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.numbers.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.numbers.q7.a" },
      { id: "b", textoKey: "exercises:english.numbers.q7.b" },
      { id: "c", textoKey: "exercises:english.numbers.q7.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-numbers-008",
    materia: "ingles",
    tema: "en_vocabulary.numbers",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.numbers.q8.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },

  // ─── Vocabulary: family ───────────────────────────────────────────────────
  {
    id: "eng-3-family-001",
    materia: "ingles",
    tema: "en_vocabulary.family",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.family.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.family.q1.a" },
      { id: "b", textoKey: "exercises:english.family.q1.b" },
      { id: "c", textoKey: "exercises:english.family.q1.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-family-002",
    materia: "ingles",
    tema: "en_vocabulary.family",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.family.q2.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "eng-3-family-003",
    materia: "ingles",
    tema: "en_vocabulary.family",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.family.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.family.q3.a" },
      { id: "b", textoKey: "exercises:english.family.q3.b" },
      { id: "c", textoKey: "exercises:english.family.q3.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "eng-3-family-004",
    materia: "ingles",
    tema: "en_vocabulary.family",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.family.q4.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "eng-3-family-005",
    materia: "ingles",
    tema: "en_vocabulary.family",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.family.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.family.q5.a" },
      { id: "b", textoKey: "exercises:english.family.q5.b" },
      { id: "c", textoKey: "exercises:english.family.q5.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "eng-3-family-006",
    materia: "ingles",
    tema: "en_vocabulary.family",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:english.family.q6.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:english.family.q6.l1" },
      { id: "l2", textoKey: "exercises:english.family.q6.l2" },
      { id: "l3", textoKey: "exercises:english.family.q6.l3" },
      { id: "r1", textoKey: "exercises:english.family.q6.r1" },
      { id: "r2", textoKey: "exercises:english.family.q6.r2" },
      { id: "r3", textoKey: "exercises:english.family.q6.r3" },
    ],
    respuestaCorrecta: ["l1:r3", "l2:r1", "l3:r2"],
    imprimible: true,
  },
  {
    id: "eng-3-family-007",
    materia: "ingles",
    tema: "en_vocabulary.family",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.family.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.family.q7.a" },
      { id: "b", textoKey: "exercises:english.family.q7.b" },
      { id: "c", textoKey: "exercises:english.family.q7.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-family-008",
    materia: "ingles",
    tema: "en_vocabulary.family",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.family.q8.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },


  // ─── Vocabulary: colours and shapes (q9+) ─────────────────────────────────
  mcE("eng-3-colors-009", "en_vocabulary.colors_shapes", "colors", "q9", "c"),
  tfE("eng-3-colors-010", "en_vocabulary.colors_shapes", "colors", "q10", "true"),
  mcE("eng-3-colors-011", "en_vocabulary.colors_shapes", "colors", "q11", "b"),
  tfE("eng-3-colors-012", "en_vocabulary.colors_shapes", "colors", "q12", "false"),
  mcE("eng-3-colors-013", "en_vocabulary.colors_shapes", "colors", "q13", "b"),
  tfE("eng-3-colors-014", "en_vocabulary.colors_shapes", "colors", "q14", "true"),
  matchE("eng-3-colors-015", "en_vocabulary.colors_shapes", "colors", "q15", ["l1:r2", "l2:r3", "l3:r1"]),
  mcE("eng-3-colors-016", "en_vocabulary.colors_shapes", "colors", "q16", "c"),
  tfE("eng-3-colors-017", "en_vocabulary.colors_shapes", "colors", "q17", "true"),
  mcE("eng-3-colors-018", "en_vocabulary.colors_shapes", "colors", "q18", "c"),
  tfE("eng-3-colors-019", "en_vocabulary.colors_shapes", "colors", "q19", "true"),
  mcE("eng-3-colors-020", "en_vocabulary.colors_shapes", "colors", "q20", "b"),
  tfE("eng-3-colors-021", "en_vocabulary.colors_shapes", "colors", "q21", "false"),
  matchE("eng-3-colors-022", "en_vocabulary.colors_shapes", "colors", "q22", ["l1:r2", "l2:r3", "l3:r1"]),
  mcE("eng-3-colors-023", "en_vocabulary.colors_shapes", "colors", "q23", "a"),
  tfE("eng-3-colors-024", "en_vocabulary.colors_shapes", "colors", "q24", "true"),
  mcE("eng-3-colors-025", "en_vocabulary.colors_shapes", "colors", "q25", "c"),
  tfE("eng-3-colors-026", "en_vocabulary.colors_shapes", "colors", "q26", "false"),
  mcE("eng-3-colors-027", "en_vocabulary.colors_shapes", "colors", "q27", "b"),
  tfE("eng-3-colors-028", "en_vocabulary.colors_shapes", "colors", "q28", "true"),
  matchE("eng-3-colors-029", "en_vocabulary.colors_shapes", "colors", "q29", ["l1:r2", "l2:r1", "l3:r3"]),
  mcE("eng-3-colors-030", "en_vocabulary.colors_shapes", "colors", "q30", "c"),
  tfE("eng-3-colors-031", "en_vocabulary.colors_shapes", "colors", "q31", "false"),
  mcE("eng-3-colors-032", "en_vocabulary.colors_shapes", "colors", "q32", "a"),
  tfE("eng-3-colors-033", "en_vocabulary.colors_shapes", "colors", "q33", "true"),
  mcE("eng-3-colors-034", "en_vocabulary.colors_shapes", "colors", "q34", "c"),
  tfE("eng-3-colors-035", "en_vocabulary.colors_shapes", "colors", "q35", "false"),
  matchE("eng-3-colors-036", "en_vocabulary.colors_shapes", "colors", "q36", ["l1:r2", "l2:r1", "l3:r3"]),
  mcE("eng-3-colors-037", "en_vocabulary.colors_shapes", "colors", "q37", "b"),
  tfE("eng-3-colors-038", "en_vocabulary.colors_shapes", "colors", "q38", "true"),
  mcE("eng-3-colors-039", "en_vocabulary.colors_shapes", "colors", "q39", "c"),
  tfE("eng-3-colors-040", "en_vocabulary.colors_shapes", "colors", "q40", "true"),
  mcE("eng-3-colors-041", "en_vocabulary.colors_shapes", "colors", "q41", "b"),
  tfE("eng-3-colors-042", "en_vocabulary.colors_shapes", "colors", "q42", "true"),
  mcE("eng-3-colors-043", "en_vocabulary.colors_shapes", "colors", "q43", "c"),
  tfE("eng-3-colors-044", "en_vocabulary.colors_shapes", "colors", "q44", "true"),
  matchE("eng-3-colors-045", "en_vocabulary.colors_shapes", "colors", "q45", ["l1:r2", "l2:r1", "l3:r3"]),
  mcE("eng-3-colors-046", "en_vocabulary.colors_shapes", "colors", "q46", "b"),
  tfE("eng-3-colors-047", "en_vocabulary.colors_shapes", "colors", "q47", "true"),
  mcE("eng-3-colors-048", "en_vocabulary.colors_shapes", "colors", "q48", "b"),
  tfE("eng-3-colors-049", "en_vocabulary.colors_shapes", "colors", "q49", "true"),
  mcE("eng-3-colors-050", "en_vocabulary.colors_shapes", "colors", "q50", "c"),
  tfE("eng-3-colors-051", "en_vocabulary.colors_shapes", "colors", "q51", "true"),
  mcE("eng-3-colors-052", "en_vocabulary.colors_shapes", "colors", "q52", "b"),

  // ─── Vocabulary: animals (q9+) ─────────────────────────────────────────────
  mcE("eng-3-animals-009", "en_vocabulary.animals", "animals", "q9", "b"),
  tfE("eng-3-animals-010", "en_vocabulary.animals", "animals", "q10", "false"),
  mcE("eng-3-animals-011", "en_vocabulary.animals", "animals", "q11", "b"),
  tfE("eng-3-animals-012", "en_vocabulary.animals", "animals", "q12", "true"),
  matchE("eng-3-animals-013", "en_vocabulary.animals", "animals", "q13", ["l1:r2", "l2:r3", "l3:r1"]),
  mcE("eng-3-animals-014", "en_vocabulary.animals", "animals", "q14", "b"),
  tfE("eng-3-animals-015", "en_vocabulary.animals", "animals", "q15", "false"),
  mcE("eng-3-animals-016", "en_vocabulary.animals", "animals", "q16", "c"),
  tfE("eng-3-animals-017", "en_vocabulary.animals", "animals", "q17", "true"),
  matchE("eng-3-animals-018", "en_vocabulary.animals", "animals", "q18", ["l1:r3", "l2:r2", "l3:r1"]),
  mcE("eng-3-animals-019", "en_vocabulary.animals", "animals", "q19", "a"),
  tfE("eng-3-animals-020", "en_vocabulary.animals", "animals", "q20", "true"),
  mcE("eng-3-animals-021", "en_vocabulary.animals", "animals", "q21", "b"),
  tfE("eng-3-animals-022", "en_vocabulary.animals", "animals", "q22", "false"),
  matchE("eng-3-animals-023", "en_vocabulary.animals", "animals", "q23", ["l1:r3", "l2:r1", "l3:r2"]),
  mcE("eng-3-animals-024", "en_vocabulary.animals", "animals", "q24", "b"),
  tfE("eng-3-animals-025", "en_vocabulary.animals", "animals", "q25", "false"),
  mcE("eng-3-animals-026", "en_vocabulary.animals", "animals", "q26", "c"),
  tfE("eng-3-animals-027", "en_vocabulary.animals", "animals", "q27", "true"),
  matchE("eng-3-animals-028", "en_vocabulary.animals", "animals", "q28", ["l1:r2", "l2:r1", "l3:r3"]),
  mcE("eng-3-animals-029", "en_vocabulary.animals", "animals", "q29", "b"),
  tfE("eng-3-animals-030", "en_vocabulary.animals", "animals", "q30", "true"),
  mcE("eng-3-animals-031", "en_vocabulary.animals", "animals", "q31", "c"),
  tfE("eng-3-animals-032", "en_vocabulary.animals", "animals", "q32", "true"),
  matchE("eng-3-animals-033", "en_vocabulary.animals", "animals", "q33", ["l1:r2", "l2:r3", "l3:r1"]),
  mcE("eng-3-animals-034", "en_vocabulary.animals", "animals", "q34", "b"),
  tfE("eng-3-animals-035", "en_vocabulary.animals", "animals", "q35", "true"),
  mcE("eng-3-animals-036", "en_vocabulary.animals", "animals", "q36", "b"),
  tfE("eng-3-animals-037", "en_vocabulary.animals", "animals", "q37", "false"),
  matchE("eng-3-animals-038", "en_vocabulary.animals", "animals", "q38", ["l1:r3", "l2:r2", "l3:r1"]),
  mcE("eng-3-animals-039", "en_vocabulary.animals", "animals", "q39", "b"),
  tfE("eng-3-animals-040", "en_vocabulary.animals", "animals", "q40", "false"),
  mcE("eng-3-animals-041", "en_vocabulary.animals", "animals", "q41", "a"),
  tfE("eng-3-animals-042", "en_vocabulary.animals", "animals", "q42", "true"),
  matchE("eng-3-animals-043", "en_vocabulary.animals", "animals", "q43", ["l1:r2", "l2:r1", "l3:r3"]),
  mcE("eng-3-animals-044", "en_vocabulary.animals", "animals", "q44", "c"),
  tfE("eng-3-animals-045", "en_vocabulary.animals", "animals", "q45", "true"),
  mcE("eng-3-animals-046", "en_vocabulary.animals", "animals", "q46", "b"),
  tfE("eng-3-animals-047", "en_vocabulary.animals", "animals", "q47", "false"),
  matchE("eng-3-animals-048", "en_vocabulary.animals", "animals", "q48", ["l1:r3", "l2:r2", "l3:r1"]),
  mcE("eng-3-animals-049", "en_vocabulary.animals", "animals", "q49", "b"),
  tfE("eng-3-animals-050", "en_vocabulary.animals", "animals", "q50", "true"),
  mcE("eng-3-animals-051", "en_vocabulary.animals", "animals", "q51", "c"),

  // ─── Basics: greetings and introductions (q9+) ───────────────────────────
  mcE("eng-3-greet-009", "en_basics.greetings", "greetings", "q9", "b"),
  tfE("eng-3-greet-010", "en_basics.greetings", "greetings", "q10", "false"),
  mcE("eng-3-greet-011", "en_basics.greetings", "greetings", "q11", "b"),
  tfE("eng-3-greet-012", "en_basics.greetings", "greetings", "q12", "true"),
  matchE("eng-3-greet-013", "en_basics.greetings", "greetings", "q13", ["l1:r3", "l2:r1", "l3:r2"]),
  mcE("eng-3-greet-014", "en_basics.greetings", "greetings", "q14", "b"),
  tfE("eng-3-greet-015", "en_basics.greetings", "greetings", "q15", "true"),
  mcE("eng-3-greet-016", "en_basics.greetings", "greetings", "q16", "b"),
  tfE("eng-3-greet-017", "en_basics.greetings", "greetings", "q17", "false"),
  matchE("eng-3-greet-018", "en_basics.greetings", "greetings", "q18", ["l1:r2", "l2:r3", "l3:r1"]),
  mcE("eng-3-greet-019", "en_basics.greetings", "greetings", "q19", "a"),
  tfE("eng-3-greet-020", "en_basics.greetings", "greetings", "q20", "true"),
  mcE("eng-3-greet-021", "en_basics.greetings", "greetings", "q21", "c"),
  tfE("eng-3-greet-022", "en_basics.greetings", "greetings", "q22", "false"),
  matchE("eng-3-greet-023", "en_basics.greetings", "greetings", "q23", ["l1:r3", "l2:r2", "l3:r1"]),
  mcE("eng-3-greet-024", "en_basics.greetings", "greetings", "q24", "b"),
  tfE("eng-3-greet-025", "en_basics.greetings", "greetings", "q25", "true"),
  mcE("eng-3-greet-026", "en_basics.greetings", "greetings", "q26", "a"),
  tfE("eng-3-greet-027", "en_basics.greetings", "greetings", "q27", "true"),
  matchE("eng-3-greet-028", "en_basics.greetings", "greetings", "q28", ["l1:r3", "l2:r2", "l3:r1"]),
  mcE("eng-3-greet-029", "en_basics.greetings", "greetings", "q29", "b"),
  tfE("eng-3-greet-030", "en_basics.greetings", "greetings", "q30", "true"),
  mcE("eng-3-greet-031", "en_basics.greetings", "greetings", "q31", "c"),
  tfE("eng-3-greet-032", "en_basics.greetings", "greetings", "q32", "true"),
  matchE("eng-3-greet-033", "en_basics.greetings", "greetings", "q33", ["l1:r2", "l2:r3", "l3:r1"]),
  mcE("eng-3-greet-034", "en_basics.greetings", "greetings", "q34", "b"),
  tfE("eng-3-greet-035", "en_basics.greetings", "greetings", "q35", "true"),
  mcE("eng-3-greet-036", "en_basics.greetings", "greetings", "q36", "b"),
  tfE("eng-3-greet-037", "en_basics.greetings", "greetings", "q37", "true"),
  matchE("eng-3-greet-038", "en_basics.greetings", "greetings", "q38", ["l1:r2", "l2:r3", "l3:r1"]),
  mcE("eng-3-greet-039", "en_basics.greetings", "greetings", "q39", "b"),
  tfE("eng-3-greet-040", "en_basics.greetings", "greetings", "q40", "true"),
  mcE("eng-3-greet-041", "en_basics.greetings", "greetings", "q41", "a"),
  tfE("eng-3-greet-042", "en_basics.greetings", "greetings", "q42", "false"),
  matchE("eng-3-greet-043", "en_basics.greetings", "greetings", "q43", ["l1:r2", "l2:r3", "l3:r1"]),
  mcE("eng-3-greet-044", "en_basics.greetings", "greetings", "q44", "a"),
  tfE("eng-3-greet-045", "en_basics.greetings", "greetings", "q45", "false"),
  mcE("eng-3-greet-046", "en_basics.greetings", "greetings", "q46", "b"),
  tfE("eng-3-greet-047", "en_basics.greetings", "greetings", "q47", "false"),
  matchE("eng-3-greet-048", "en_basics.greetings", "greetings", "q48", ["l1:r3", "l2:r2", "l3:r1"]),
  mcE("eng-3-greet-049", "en_basics.greetings", "greetings", "q49", "a"),
  tfE("eng-3-greet-050", "en_basics.greetings", "greetings", "q50", "true"),
  mcE("eng-3-greet-051", "en_basics.greetings", "greetings", "q51", "b"),

  // ─── Basics: numbers (q9+) ──────────────────────────────────────────────
  mcE("eng-3-numbers-009", "en_basics.numbers", "numbers", "q9", "a"),
  tfE("eng-3-numbers-010", "en_basics.numbers", "numbers", "q10", "true"),
  mcE("eng-3-numbers-011", "en_basics.numbers", "numbers", "q11", "b"),
  tfE("eng-3-numbers-012", "en_basics.numbers", "numbers", "q12", "true"),
  matchE("eng-3-numbers-013", "en_basics.numbers", "numbers", "q13", ["l1:r2", "l2:r3", "l3:r1"]),
  mcE("eng-3-numbers-014", "en_basics.numbers", "numbers", "q14", "b"),
  tfE("eng-3-numbers-015", "en_basics.numbers", "numbers", "q15", "false"),
  mcE("eng-3-numbers-016", "en_basics.numbers", "numbers", "q16", "b"),
  tfE("eng-3-numbers-017", "en_basics.numbers", "numbers", "q17", "false"),
  matchE("eng-3-numbers-018", "en_basics.numbers", "numbers", "q18", ["l1:r2", "l2:r1", "l3:r3"]),
  mcE("eng-3-numbers-019", "en_basics.numbers", "numbers", "q19", "a"),
  tfE("eng-3-numbers-020", "en_basics.numbers", "numbers", "q20", "true"),
  mcE("eng-3-numbers-021", "en_basics.numbers", "numbers", "q21", "a"),
  tfE("eng-3-numbers-022", "en_basics.numbers", "numbers", "q22", "true"),
  matchE("eng-3-numbers-023", "en_basics.numbers", "numbers", "q23", ["l1:r2", "l2:r3", "l3:r1"]),
  mcE("eng-3-numbers-024", "en_basics.numbers", "numbers", "q24", "b"),
  tfE("eng-3-numbers-025", "en_basics.numbers", "numbers", "q25", "false"),
  mcE("eng-3-numbers-026", "en_basics.numbers", "numbers", "q26", "b"),
  tfE("eng-3-numbers-027", "en_basics.numbers", "numbers", "q27", "true"),
  matchE("eng-3-numbers-028", "en_basics.numbers", "numbers", "q28", ["l1:r2", "l2:r3", "l3:r1"]),
  mcE("eng-3-numbers-029", "en_basics.numbers", "numbers", "q29", "b"),
  tfE("eng-3-numbers-030", "en_basics.numbers", "numbers", "q30", "true"),
  mcE("eng-3-numbers-031", "en_basics.numbers", "numbers", "q31", "b"),
  tfE("eng-3-numbers-032", "en_basics.numbers", "numbers", "q32", "true"),
  matchE("eng-3-numbers-033", "en_basics.numbers", "numbers", "q33", ["l1:r2", "l2:r3", "l3:r1"]),
  mcE("eng-3-numbers-034", "en_basics.numbers", "numbers", "q34", "c"),
  tfE("eng-3-numbers-035", "en_basics.numbers", "numbers", "q35", "true"),
  mcE("eng-3-numbers-036", "en_basics.numbers", "numbers", "q36", "b"),
  tfE("eng-3-numbers-037", "en_basics.numbers", "numbers", "q37", "false"),
  matchE("eng-3-numbers-038", "en_basics.numbers", "numbers", "q38", ["l1:r2", "l2:r1", "l3:r3"]),
  mcE("eng-3-numbers-039", "en_basics.numbers", "numbers", "q39", "b"),
  tfE("eng-3-numbers-040", "en_basics.numbers", "numbers", "q40", "true"),
  mcE("eng-3-numbers-041", "en_basics.numbers", "numbers", "q41", "c"),
  tfE("eng-3-numbers-042", "en_basics.numbers", "numbers", "q42", "true"),
  matchE("eng-3-numbers-043", "en_basics.numbers", "numbers", "q43", ["l1:r3", "l2:r1", "l3:r2"]),
  mcE("eng-3-numbers-044", "en_basics.numbers", "numbers", "q44", "c"),
  tfE("eng-3-numbers-045", "en_basics.numbers", "numbers", "q45", "true"),
  mcE("eng-3-numbers-046", "en_basics.numbers", "numbers", "q46", "b"),
  tfE("eng-3-numbers-047", "en_basics.numbers", "numbers", "q47", "true"),
  matchE("eng-3-numbers-048", "en_basics.numbers", "numbers", "q48", ["l1:r3", "l2:r1", "l3:r2"]),
  mcE("eng-3-numbers-049", "en_basics.numbers", "numbers", "q49", "a"),
  tfE("eng-3-numbers-050", "en_basics.numbers", "numbers", "q50", "true"),
  mcE("eng-3-numbers-051", "en_basics.numbers", "numbers", "q51", "b"),

  // ─── Vocabulary: family (q9+) ───────────────────────────────────────────
  mcE("eng-3-family-009", "en_vocabulary.family", "family", "q9", "c"),
  tfE("eng-3-family-010", "en_vocabulary.family", "family", "q10", "true"),
  mcE("eng-3-family-011", "en_vocabulary.family", "family", "q11", "b"),
  tfE("eng-3-family-012", "en_vocabulary.family", "family", "q12", "true"),
  matchE("eng-3-family-013", "en_vocabulary.family", "family", "q13", ["l1:r3", "l2:r1", "l3:r2"]),
  mcE("eng-3-family-014", "en_vocabulary.family", "family", "q14", "c"),
  tfE("eng-3-family-015", "en_vocabulary.family", "family", "q15", "true"),
  mcE("eng-3-family-016", "en_vocabulary.family", "family", "q16", "a"),
  tfE("eng-3-family-017", "en_vocabulary.family", "family", "q17", "true"),
  matchE("eng-3-family-018", "en_vocabulary.family", "family", "q18", ["l1:r2", "l2:r3", "l3:r1"]),
  mcE("eng-3-family-019", "en_vocabulary.family", "family", "q19", "c"),
  tfE("eng-3-family-020", "en_vocabulary.family", "family", "q20", "true"),
  mcE("eng-3-family-021", "en_vocabulary.family", "family", "q21", "a"),
  tfE("eng-3-family-022", "en_vocabulary.family", "family", "q22", "true"),
  matchE("eng-3-family-023", "en_vocabulary.family", "family", "q23", ["l1:r3", "l2:r2", "l3:r1"]),
  mcE("eng-3-family-024", "en_vocabulary.family", "family", "q24", "b"),
  tfE("eng-3-family-025", "en_vocabulary.family", "family", "q25", "true"),
  mcE("eng-3-family-026", "en_vocabulary.family", "family", "q26", "b"),
  tfE("eng-3-family-027", "en_vocabulary.family", "family", "q27", "true"),
  matchE("eng-3-family-028", "en_vocabulary.family", "family", "q28", ["l1:r2", "l2:r3", "l3:r1"]),
  mcE("eng-3-family-029", "en_vocabulary.family", "family", "q29", "c"),
  tfE("eng-3-family-030", "en_vocabulary.family", "family", "q30", "true"),
  mcE("eng-3-family-031", "en_vocabulary.family", "family", "q31", "b"),
  tfE("eng-3-family-032", "en_vocabulary.family", "family", "q32", "true"),
  matchE("eng-3-family-033", "en_vocabulary.family", "family", "q33", ["l1:r2", "l2:r3", "l3:r1"]),
  mcE("eng-3-family-034", "en_vocabulary.family", "family", "q34", "c"),
  tfE("eng-3-family-035", "en_vocabulary.family", "family", "q35", "true"),
  mcE("eng-3-family-036", "en_vocabulary.family", "family", "q36", "b"),
  tfE("eng-3-family-037", "en_vocabulary.family", "family", "q37", "true"),
  matchE("eng-3-family-038", "en_vocabulary.family", "family", "q38", ["l1:r3", "l2:r2", "l3:r1"]),
  mcE("eng-3-family-039", "en_vocabulary.family", "family", "q39", "b"),
  tfE("eng-3-family-040", "en_vocabulary.family", "family", "q40", "true"),
  mcE("eng-3-family-041", "en_vocabulary.family", "family", "q41", "c"),
  tfE("eng-3-family-042", "en_vocabulary.family", "family", "q42", "true"),
  matchE("eng-3-family-043", "en_vocabulary.family", "family", "q43", ["l1:r2", "l2:r3", "l3:r1"]),
  mcE("eng-3-family-044", "en_vocabulary.family", "family", "q44", "b"),
  tfE("eng-3-family-045", "en_vocabulary.family", "family", "q45", "true"),
  mcE("eng-3-family-046", "en_vocabulary.family", "family", "q46", "b"),
  tfE("eng-3-family-047", "en_vocabulary.family", "family", "q47", "true"),
  matchE("eng-3-family-048", "en_vocabulary.family", "family", "q48", ["l1:r3", "l2:r2", "l3:r1"]),
  mcE("eng-3-family-049", "en_vocabulary.family", "family", "q49", "b"),
  tfE("eng-3-family-050", "en_vocabulary.family", "family", "q50", "true"),
  mcE("eng-3-family-051", "en_vocabulary.family", "family", "q51", "c"),

];
