/*
 * English subject content — naturally in English. Like Spanish and Natural
 * Science, its content does NOT follow the UI language selector. Its i18n keys
 * only exist in EN. Original content.
 */
import type { EjercicioAny } from "../types";

export const ingles: EjercicioAny[] = [

  // ─── Vocabulary: colours and shapes ──────────────────────────────────────
  {
    id: "eng-3-colors-001",
    materia: "ingles",
    tema: "en_vocabulary.colors_shapes",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.colors.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.colors.q1.a" },
      { id: "b", textoKey: "exercises:english.colors.q1.b" },
      { id: "c", textoKey: "exercises:english.colors.q1.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "eng-3-colors-002",
    materia: "ingles",
    tema: "en_vocabulary.colors_shapes",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:english.colors.q2.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:english.colors.q2.l1" },
      { id: "l2", textoKey: "exercises:english.colors.q2.l2" },
      { id: "l3", textoKey: "exercises:english.colors.q2.l3" },
      { id: "r1", textoKey: "exercises:english.colors.q2.r1" },
      { id: "r2", textoKey: "exercises:english.colors.q2.r2" },
      { id: "r3", textoKey: "exercises:english.colors.q2.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r3", "l3:r1"],
    imprimible: true,
  },
  {
    id: "eng-3-colors-003",
    materia: "ingles",
    tema: "en_vocabulary.colors_shapes",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.colors.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.colors.q3.a" },
      { id: "b", textoKey: "exercises:english.colors.q3.b" },
      { id: "c", textoKey: "exercises:english.colors.q3.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "eng-3-colors-004",
    materia: "ingles",
    tema: "en_vocabulary.colors_shapes",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.colors.q4.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "eng-3-colors-005",
    materia: "ingles",
    tema: "en_vocabulary.colors_shapes",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.colors.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.colors.q5.a" },
      { id: "b", textoKey: "exercises:english.colors.q5.b" },
      { id: "c", textoKey: "exercises:english.colors.q5.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-colors-006",
    materia: "ingles",
    tema: "en_vocabulary.colors_shapes",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.colors.q6.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "eng-3-colors-007",
    materia: "ingles",
    tema: "en_vocabulary.colors_shapes",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.colors.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.colors.q7.a" },
      { id: "b", textoKey: "exercises:english.colors.q7.b" },
      { id: "c", textoKey: "exercises:english.colors.q7.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-colors-008",
    materia: "ingles",
    tema: "en_vocabulary.colors_shapes",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:english.colors.q8.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:english.colors.q8.l1" },
      { id: "l2", textoKey: "exercises:english.colors.q8.l2" },
      { id: "l3", textoKey: "exercises:english.colors.q8.l3" },
      { id: "r1", textoKey: "exercises:english.colors.q8.r1" },
      { id: "r2", textoKey: "exercises:english.colors.q8.r2" },
      { id: "r3", textoKey: "exercises:english.colors.q8.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r3", "l3:r1"],
    imprimible: true,
  },

  // ─── Vocabulary: animals ──────────────────────────────────────────────────
  {
    id: "eng-3-animals-001",
    materia: "ingles",
    tema: "en_vocabulary.animals",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.animals.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.animals.q1.a" },
      { id: "b", textoKey: "exercises:english.animals.q1.b" },
      { id: "c", textoKey: "exercises:english.animals.q1.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "eng-3-animals-002",
    materia: "ingles",
    tema: "en_vocabulary.animals",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.animals.q2.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "eng-3-animals-003",
    materia: "ingles",
    tema: "en_vocabulary.animals",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.animals.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.animals.q3.a" },
      { id: "b", textoKey: "exercises:english.animals.q3.b" },
      { id: "c", textoKey: "exercises:english.animals.q3.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "eng-3-animals-004",
    materia: "ingles",
    tema: "en_vocabulary.animals",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.animals.q4.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "eng-3-animals-005",
    materia: "ingles",
    tema: "en_vocabulary.animals",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.animals.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.animals.q5.a" },
      { id: "b", textoKey: "exercises:english.animals.q5.b" },
      { id: "c", textoKey: "exercises:english.animals.q5.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-animals-006",
    materia: "ingles",
    tema: "en_vocabulary.animals",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.animals.q6.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "eng-3-animals-007",
    materia: "ingles",
    tema: "en_vocabulary.animals",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:english.animals.q7.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:english.animals.q7.l1" },
      { id: "l2", textoKey: "exercises:english.animals.q7.l2" },
      { id: "l3", textoKey: "exercises:english.animals.q7.l3" },
      { id: "r1", textoKey: "exercises:english.animals.q7.r1" },
      { id: "r2", textoKey: "exercises:english.animals.q7.r2" },
      { id: "r3", textoKey: "exercises:english.animals.q7.r3" },
    ],
    respuestaCorrecta: ["l1:r3", "l2:r1", "l3:r2"],
    imprimible: true,
  },
  {
    id: "eng-3-animals-008",
    materia: "ingles",
    tema: "en_vocabulary.animals",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.animals.q8.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.animals.q8.a" },
      { id: "b", textoKey: "exercises:english.animals.q8.b" },
      { id: "c", textoKey: "exercises:english.animals.q8.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },

  // ─── Basics: greetings and introductions ──────────────────────────────────
  {
    id: "eng-3-greet-001",
    materia: "ingles",
    tema: "en_basics.greetings",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.greetings.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.greetings.q1.a" },
      { id: "b", textoKey: "exercises:english.greetings.q1.b" },
      { id: "c", textoKey: "exercises:english.greetings.q1.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-greet-002",
    materia: "ingles",
    tema: "en_basics.greetings",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.greetings.q2.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.greetings.q2.a" },
      { id: "b", textoKey: "exercises:english.greetings.q2.b" },
      { id: "c", textoKey: "exercises:english.greetings.q2.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "eng-3-greet-003",
    materia: "ingles",
    tema: "en_basics.greetings",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.greetings.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.greetings.q3.a" },
      { id: "b", textoKey: "exercises:english.greetings.q3.b" },
      { id: "c", textoKey: "exercises:english.greetings.q3.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-greet-004",
    materia: "ingles",
    tema: "en_basics.greetings",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.greetings.q4.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "eng-3-greet-005",
    materia: "ingles",
    tema: "en_basics.greetings",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.greetings.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.greetings.q5.a" },
      { id: "b", textoKey: "exercises:english.greetings.q5.b" },
      { id: "c", textoKey: "exercises:english.greetings.q5.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-greet-006",
    materia: "ingles",
    tema: "en_basics.greetings",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.greetings.q6.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "eng-3-greet-007",
    materia: "ingles",
    tema: "en_basics.greetings",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.greetings.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.greetings.q7.a" },
      { id: "b", textoKey: "exercises:english.greetings.q7.b" },
      { id: "c", textoKey: "exercises:english.greetings.q7.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "eng-3-greet-008",
    materia: "ingles",
    tema: "en_basics.greetings",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:english.greetings.q8.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:english.greetings.q8.l1" },
      { id: "l2", textoKey: "exercises:english.greetings.q8.l2" },
      { id: "l3", textoKey: "exercises:english.greetings.q8.l3" },
      { id: "r1", textoKey: "exercises:english.greetings.q8.r1" },
      { id: "r2", textoKey: "exercises:english.greetings.q8.r2" },
      { id: "r3", textoKey: "exercises:english.greetings.q8.r3" },
    ],
    respuestaCorrecta: ["l1:r3", "l2:r1", "l3:r2"],
    imprimible: true,
  },

  // ─── Vocabulary: numbers ──────────────────────────────────────────────────
  {
    id: "eng-3-numbers-001",
    materia: "ingles",
    tema: "en_vocabulary.numbers",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.numbers.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.numbers.q1.a" },
      { id: "b", textoKey: "exercises:english.numbers.q1.b" },
      { id: "c", textoKey: "exercises:english.numbers.q1.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-numbers-002",
    materia: "ingles",
    tema: "en_vocabulary.numbers",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.numbers.q2.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "eng-3-numbers-003",
    materia: "ingles",
    tema: "en_vocabulary.numbers",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.numbers.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.numbers.q3.a" },
      { id: "b", textoKey: "exercises:english.numbers.q3.b" },
      { id: "c", textoKey: "exercises:english.numbers.q3.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-numbers-004",
    materia: "ingles",
    tema: "en_vocabulary.numbers",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.numbers.q4.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "eng-3-numbers-005",
    materia: "ingles",
    tema: "en_vocabulary.numbers",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.numbers.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.numbers.q5.a" },
      { id: "b", textoKey: "exercises:english.numbers.q5.b" },
      { id: "c", textoKey: "exercises:english.numbers.q5.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "eng-3-numbers-006",
    materia: "ingles",
    tema: "en_vocabulary.numbers",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:english.numbers.q6.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:english.numbers.q6.l1" },
      { id: "l2", textoKey: "exercises:english.numbers.q6.l2" },
      { id: "l3", textoKey: "exercises:english.numbers.q6.l3" },
      { id: "r1", textoKey: "exercises:english.numbers.q6.r1" },
      { id: "r2", textoKey: "exercises:english.numbers.q6.r2" },
      { id: "r3", textoKey: "exercises:english.numbers.q6.r3" },
    ],
    respuestaCorrecta: ["l1:r3", "l2:r1", "l3:r2"],
    imprimible: true,
  },
  {
    id: "eng-3-numbers-007",
    materia: "ingles",
    tema: "en_vocabulary.numbers",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.numbers.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.numbers.q7.a" },
      { id: "b", textoKey: "exercises:english.numbers.q7.b" },
      { id: "c", textoKey: "exercises:english.numbers.q7.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-numbers-008",
    materia: "ingles",
    tema: "en_vocabulary.numbers",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.numbers.q8.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },

  // ─── Vocabulary: family ───────────────────────────────────────────────────
  {
    id: "eng-3-family-001",
    materia: "ingles",
    tema: "en_vocabulary.family",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.family.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.family.q1.a" },
      { id: "b", textoKey: "exercises:english.family.q1.b" },
      { id: "c", textoKey: "exercises:english.family.q1.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-family-002",
    materia: "ingles",
    tema: "en_vocabulary.family",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.family.q2.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "eng-3-family-003",
    materia: "ingles",
    tema: "en_vocabulary.family",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.family.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.family.q3.a" },
      { id: "b", textoKey: "exercises:english.family.q3.b" },
      { id: "c", textoKey: "exercises:english.family.q3.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "eng-3-family-004",
    materia: "ingles",
    tema: "en_vocabulary.family",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.family.q4.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "eng-3-family-005",
    materia: "ingles",
    tema: "en_vocabulary.family",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.family.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.family.q5.a" },
      { id: "b", textoKey: "exercises:english.family.q5.b" },
      { id: "c", textoKey: "exercises:english.family.q5.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "eng-3-family-006",
    materia: "ingles",
    tema: "en_vocabulary.family",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:english.family.q6.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:english.family.q6.l1" },
      { id: "l2", textoKey: "exercises:english.family.q6.l2" },
      { id: "l3", textoKey: "exercises:english.family.q6.l3" },
      { id: "r1", textoKey: "exercises:english.family.q6.r1" },
      { id: "r2", textoKey: "exercises:english.family.q6.r2" },
      { id: "r3", textoKey: "exercises:english.family.q6.r3" },
    ],
    respuestaCorrecta: ["l1:r3", "l2:r1", "l3:r2"],
    imprimible: true,
  },
  {
    id: "eng-3-family-007",
    materia: "ingles",
    tema: "en_vocabulary.family",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:english.family.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:english.family.q7.a" },
      { id: "b", textoKey: "exercises:english.family.q7.b" },
      { id: "c", textoKey: "exercises:english.family.q7.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "eng-3-family-008",
    materia: "ingles",
    tema: "en_vocabulary.family",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:english.family.q8.prompt",
    opciones: [
      { id: "true", textoKey: "exercises:english.common.true" },
      { id: "false", textoKey: "exercises:english.common.false" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
];
