/*
 * Contenido real de Lengua Castellana.
 * Específico del idioma castellano: NO se traduce (D-1). Las claves i18n de este
 * contenido sólo existen en ES; con cualquier idioma de UI se muestran en ES.
 * Contenido original.
 */
import type { EjercicioAny } from "../types";

export const lengua: EjercicioAny[] = [

  // ─── Sinónimos y antónimos ────────────────────────────────────────────────
  {
    id: "len-3-syn-001",
    materia: "lengua",
    tema: "vocabulary.synonyms_antonyms",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.syn.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.syn.q1.a" },
      { id: "b", textoKey: "exercises:spanish.syn.q1.b" },
      { id: "c", textoKey: "exercises:spanish.syn.q1.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "len-3-syn-002",
    materia: "lengua",
    tema: "vocabulary.synonyms_antonyms",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:spanish.syn.q2.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:spanish.syn.q2.l1" },
      { id: "l2", textoKey: "exercises:spanish.syn.q2.l2" },
      { id: "l3", textoKey: "exercises:spanish.syn.q2.l3" },
      { id: "r1", textoKey: "exercises:spanish.syn.q2.r1" },
      { id: "r2", textoKey: "exercises:spanish.syn.q2.r2" },
      { id: "r3", textoKey: "exercises:spanish.syn.q2.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r3", "l3:r1"],
    imprimible: true,
  },
  {
    id: "len-3-syn-003",
    materia: "lengua",
    tema: "vocabulary.synonyms_antonyms",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.syn.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.syn.q3.a" },
      { id: "b", textoKey: "exercises:spanish.syn.q3.b" },
      { id: "c", textoKey: "exercises:spanish.syn.q3.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "len-3-syn-004",
    materia: "lengua",
    tema: "vocabulary.synonyms_antonyms",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:spanish.syn.q4.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "len-3-syn-005",
    materia: "lengua",
    tema: "vocabulary.synonyms_antonyms",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.syn.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.syn.q5.a" },
      { id: "b", textoKey: "exercises:spanish.syn.q5.b" },
      { id: "c", textoKey: "exercises:spanish.syn.q5.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "len-3-syn-006",
    materia: "lengua",
    tema: "vocabulary.synonyms_antonyms",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:spanish.syn.q6.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "len-3-syn-007",
    materia: "lengua",
    tema: "vocabulary.synonyms_antonyms",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:spanish.syn.q7.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:spanish.syn.q7.l1" },
      { id: "l2", textoKey: "exercises:spanish.syn.q7.l2" },
      { id: "l3", textoKey: "exercises:spanish.syn.q7.l3" },
      { id: "r1", textoKey: "exercises:spanish.syn.q7.r1" },
      { id: "r2", textoKey: "exercises:spanish.syn.q7.r2" },
      { id: "r3", textoKey: "exercises:spanish.syn.q7.r3" },
    ],
    respuestaCorrecta: ["l1:r3", "l2:r1", "l3:r2"],
    imprimible: true,
  },
  {
    id: "len-3-syn-008",
    materia: "lengua",
    tema: "vocabulary.synonyms_antonyms",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.syn.q8.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.syn.q8.a" },
      { id: "b", textoKey: "exercises:spanish.syn.q8.b" },
      { id: "c", textoKey: "exercises:spanish.syn.q8.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "len-3-syn-009",
    materia: "lengua",
    tema: "vocabulary.synonyms_antonyms",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.syn.q9.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.syn.q9.a" },
      { id: "b", textoKey: "exercises:spanish.syn.q9.b" },
      { id: "c", textoKey: "exercises:spanish.syn.q9.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "len-3-syn-010",
    materia: "lengua",
    tema: "vocabulary.synonyms_antonyms",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:spanish.syn.q10.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:spanish.syn.q10.l1" },
      { id: "l2", textoKey: "exercises:spanish.syn.q10.l2" },
      { id: "l3", textoKey: "exercises:spanish.syn.q10.l3" },
      { id: "r1", textoKey: "exercises:spanish.syn.q10.r1" },
      { id: "r2", textoKey: "exercises:spanish.syn.q10.r2" },
      { id: "r3", textoKey: "exercises:spanish.syn.q10.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r1", "l3:r3"],
    imprimible: true,
  },

  // ─── El sustantivo: género y número ──────────────────────────────────────
  {
    id: "len-3-noun-001",
    materia: "lengua",
    tema: "grammar.noun",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.noun.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.noun.q1.a" },
      { id: "b", textoKey: "exercises:spanish.noun.q1.b" },
      { id: "c", textoKey: "exercises:spanish.noun.q1.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "len-3-noun-002",
    materia: "lengua",
    tema: "grammar.noun",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:spanish.noun.q2.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "len-3-noun-003",
    materia: "lengua",
    tema: "grammar.noun",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.noun.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.noun.q3.a" },
      { id: "b", textoKey: "exercises:spanish.noun.q3.b" },
      { id: "c", textoKey: "exercises:spanish.noun.q3.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "len-3-noun-004",
    materia: "lengua",
    tema: "grammar.noun",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:spanish.noun.q4.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "len-3-noun-005",
    materia: "lengua",
    tema: "grammar.noun",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.noun.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.noun.q5.a" },
      { id: "b", textoKey: "exercises:spanish.noun.q5.b" },
      { id: "c", textoKey: "exercises:spanish.noun.q5.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "len-3-noun-006",
    materia: "lengua",
    tema: "grammar.noun",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:spanish.noun.q6.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:spanish.noun.q6.l1" },
      { id: "l2", textoKey: "exercises:spanish.noun.q6.l2" },
      { id: "l3", textoKey: "exercises:spanish.noun.q6.l3" },
      { id: "r1", textoKey: "exercises:spanish.noun.q6.r1" },
      { id: "r2", textoKey: "exercises:spanish.noun.q6.r2" },
      { id: "r3", textoKey: "exercises:spanish.noun.q6.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r3", "l3:r1"],
    imprimible: true,
  },
  {
    id: "len-3-noun-007",
    materia: "lengua",
    tema: "grammar.noun",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.noun.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.noun.q7.a" },
      { id: "b", textoKey: "exercises:spanish.noun.q7.b" },
      { id: "c", textoKey: "exercises:spanish.noun.q7.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "len-3-noun-008",
    materia: "lengua",
    tema: "grammar.noun",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:spanish.noun.q8.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "len-3-noun-009",
    materia: "lengua",
    tema: "grammar.noun",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.noun.q9.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.noun.q9.a" },
      { id: "b", textoKey: "exercises:spanish.noun.q9.b" },
      { id: "c", textoKey: "exercises:spanish.noun.q9.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "len-3-noun-010",
    materia: "lengua",
    tema: "grammar.noun",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.noun.q10.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.noun.q10.a" },
      { id: "b", textoKey: "exercises:spanish.noun.q10.b" },
      { id: "c", textoKey: "exercises:spanish.noun.q10.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },

  // ─── Ortografía: mp / mb ──────────────────────────────────────────────────
  {
    id: "len-3-mpmb-001",
    materia: "lengua",
    tema: "spelling.mp_mb",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.mpmb.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.mpmb.q1.a" },
      { id: "b", textoKey: "exercises:spanish.mpmb.q1.b" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "len-3-mpmb-002",
    materia: "lengua",
    tema: "spelling.mp_mb",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.mpmb.q2.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.mpmb.q2.a" },
      { id: "b", textoKey: "exercises:spanish.mpmb.q2.b" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "len-3-mpmb-003",
    materia: "lengua",
    tema: "spelling.mp_mb",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:spanish.mpmb.q3.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "len-3-mpmb-004",
    materia: "lengua",
    tema: "spelling.mp_mb",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:spanish.mpmb.q4.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "len-3-mpmb-005",
    materia: "lengua",
    tema: "spelling.mp_mb",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.mpmb.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.mpmb.q5.a" },
      { id: "b", textoKey: "exercises:spanish.mpmb.q5.b" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "len-3-mpmb-006",
    materia: "lengua",
    tema: "spelling.mp_mb",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.mpmb.q6.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.mpmb.q6.a" },
      { id: "b", textoKey: "exercises:spanish.mpmb.q6.b" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "len-3-mpmb-007",
    materia: "lengua",
    tema: "spelling.mp_mb",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:spanish.mpmb.q7.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:spanish.mpmb.q7.l1" },
      { id: "l2", textoKey: "exercises:spanish.mpmb.q7.l2" },
      { id: "l3", textoKey: "exercises:spanish.mpmb.q7.l3" },
      { id: "r1", textoKey: "exercises:spanish.mpmb.q7.r1" },
      { id: "r2", textoKey: "exercises:spanish.mpmb.q7.r2" },
      { id: "r3", textoKey: "exercises:spanish.mpmb.q7.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r1", "l3:r3"],
    imprimible: true,
  },
  {
    id: "len-3-mpmb-008",
    materia: "lengua",
    tema: "spelling.mp_mb",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.mpmb.q8.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.mpmb.q8.a" },
      { id: "b", textoKey: "exercises:spanish.mpmb.q8.b" },
      { id: "c", textoKey: "exercises:spanish.mpmb.q8.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },

  // ─── El adjetivo ──────────────────────────────────────────────────────────
  {
    id: "len-3-adj-001",
    materia: "lengua",
    tema: "grammar.adjective",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.adj.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.adj.q1.a" },
      { id: "b", textoKey: "exercises:spanish.adj.q1.b" },
      { id: "c", textoKey: "exercises:spanish.adj.q1.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "len-3-adj-002",
    materia: "lengua",
    tema: "grammar.adjective",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:spanish.adj.q2.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "len-3-adj-003",
    materia: "lengua",
    tema: "grammar.adjective",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.adj.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.adj.q3.a" },
      { id: "b", textoKey: "exercises:spanish.adj.q3.b" },
      { id: "c", textoKey: "exercises:spanish.adj.q3.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "len-3-adj-004",
    materia: "lengua",
    tema: "grammar.adjective",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:spanish.adj.q4.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "len-3-adj-005",
    materia: "lengua",
    tema: "grammar.adjective",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.adj.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.adj.q5.a" },
      { id: "b", textoKey: "exercises:spanish.adj.q5.b" },
      { id: "c", textoKey: "exercises:spanish.adj.q5.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "len-3-adj-006",
    materia: "lengua",
    tema: "grammar.adjective",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:spanish.adj.q6.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:spanish.adj.q6.l1" },
      { id: "l2", textoKey: "exercises:spanish.adj.q6.l2" },
      { id: "l3", textoKey: "exercises:spanish.adj.q6.l3" },
      { id: "r1", textoKey: "exercises:spanish.adj.q6.r1" },
      { id: "r2", textoKey: "exercises:spanish.adj.q6.r2" },
      { id: "r3", textoKey: "exercises:spanish.adj.q6.r3" },
    ],
    respuestaCorrecta: ["l1:r1", "l2:r3", "l3:r2"],
    imprimible: true,
  },
  {
    id: "len-3-adj-007",
    materia: "lengua",
    tema: "grammar.adjective",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.adj.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.adj.q7.a" },
      { id: "b", textoKey: "exercises:spanish.adj.q7.b" },
      { id: "c", textoKey: "exercises:spanish.adj.q7.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "len-3-adj-008",
    materia: "lengua",
    tema: "grammar.adjective",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:spanish.adj.q8.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },

  // ─── El verbo ─────────────────────────────────────────────────────────────
  {
    id: "len-3-verb-001",
    materia: "lengua",
    tema: "grammar.verb",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.verb.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.verb.q1.a" },
      { id: "b", textoKey: "exercises:spanish.verb.q1.b" },
      { id: "c", textoKey: "exercises:spanish.verb.q1.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "len-3-verb-002",
    materia: "lengua",
    tema: "grammar.verb",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:spanish.verb.q2.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "len-3-verb-003",
    materia: "lengua",
    tema: "grammar.verb",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.verb.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.verb.q3.a" },
      { id: "b", textoKey: "exercises:spanish.verb.q3.b" },
      { id: "c", textoKey: "exercises:spanish.verb.q3.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "len-3-verb-004",
    materia: "lengua",
    tema: "grammar.verb",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.verb.q4.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.verb.q4.a" },
      { id: "b", textoKey: "exercises:spanish.verb.q4.b" },
      { id: "c", textoKey: "exercises:spanish.verb.q4.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "len-3-verb-005",
    materia: "lengua",
    tema: "grammar.verb",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:spanish.verb.q5.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:spanish.verb.q5.l1" },
      { id: "l2", textoKey: "exercises:spanish.verb.q5.l2" },
      { id: "l3", textoKey: "exercises:spanish.verb.q5.l3" },
      { id: "r1", textoKey: "exercises:spanish.verb.q5.r1" },
      { id: "r2", textoKey: "exercises:spanish.verb.q5.r2" },
      { id: "r3", textoKey: "exercises:spanish.verb.q5.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r3", "l3:r1"],
    imprimible: true,
  },
  {
    id: "len-3-verb-006",
    materia: "lengua",
    tema: "grammar.verb",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:spanish.verb.q6.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "len-3-verb-007",
    materia: "lengua",
    tema: "grammar.verb",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.verb.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.verb.q7.a" },
      { id: "b", textoKey: "exercises:spanish.verb.q7.b" },
      { id: "c", textoKey: "exercises:spanish.verb.q7.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "len-3-verb-008",
    materia: "lengua",
    tema: "grammar.verb",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.verb.q8.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.verb.q8.a" },
      { id: "b", textoKey: "exercises:spanish.verb.q8.b" },
      { id: "c", textoKey: "exercises:spanish.verb.q8.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },

  // ─── Ortografía: b / v ────────────────────────────────────────────────────
  {
    id: "len-3-bv-001",
    materia: "lengua",
    tema: "spelling.b_v",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.bv.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.bv.q1.a" },
      { id: "b", textoKey: "exercises:spanish.bv.q1.b" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "len-3-bv-002",
    materia: "lengua",
    tema: "spelling.b_v",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.bv.q2.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.bv.q2.a" },
      { id: "b", textoKey: "exercises:spanish.bv.q2.b" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "len-3-bv-003",
    materia: "lengua",
    tema: "spelling.b_v",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:spanish.bv.q3.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "len-3-bv-004",
    materia: "lengua",
    tema: "spelling.b_v",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.bv.q4.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.bv.q4.a" },
      { id: "b", textoKey: "exercises:spanish.bv.q4.b" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "len-3-bv-005",
    materia: "lengua",
    tema: "spelling.b_v",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.bv.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.bv.q5.a" },
      { id: "b", textoKey: "exercises:spanish.bv.q5.b" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "len-3-bv-006",
    materia: "lengua",
    tema: "spelling.b_v",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:spanish.bv.q6.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "len-3-bv-007",
    materia: "lengua",
    tema: "spelling.b_v",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.bv.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.bv.q7.a" },
      { id: "b", textoKey: "exercises:spanish.bv.q7.b" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "len-3-bv-008",
    materia: "lengua",
    tema: "spelling.b_v",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:spanish.bv.q8.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:spanish.bv.q8.l1" },
      { id: "l2", textoKey: "exercises:spanish.bv.q8.l2" },
      { id: "l3", textoKey: "exercises:spanish.bv.q8.l3" },
      { id: "r1", textoKey: "exercises:spanish.bv.q8.r1" },
      { id: "r2", textoKey: "exercises:spanish.bv.q8.r2" },
      { id: "r3", textoKey: "exercises:spanish.bv.q8.r3" },
    ],
    respuestaCorrecta: ["l1:r3", "l2:r1", "l3:r2"],
    imprimible: true,
  },

  // ─── Acentuación: agudas, llanas y esdrújulas ────────────────────────────
  {
    id: "len-3-acc-001",
    materia: "lengua",
    tema: "spelling.accents",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.acc.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.acc.q1.a" },
      { id: "b", textoKey: "exercises:spanish.acc.q1.b" },
      { id: "c", textoKey: "exercises:spanish.acc.q1.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "len-3-acc-002",
    materia: "lengua",
    tema: "spelling.accents",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:spanish.acc.q2.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "len-3-acc-003",
    materia: "lengua",
    tema: "spelling.accents",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.acc.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.acc.q3.a" },
      { id: "b", textoKey: "exercises:spanish.acc.q3.b" },
      { id: "c", textoKey: "exercises:spanish.acc.q3.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "len-3-acc-004",
    materia: "lengua",
    tema: "spelling.accents",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:spanish.acc.q4.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:spanish.acc.q4.l1" },
      { id: "l2", textoKey: "exercises:spanish.acc.q4.l2" },
      { id: "l3", textoKey: "exercises:spanish.acc.q4.l3" },
      { id: "r1", textoKey: "exercises:spanish.acc.q4.r1" },
      { id: "r2", textoKey: "exercises:spanish.acc.q4.r2" },
      { id: "r3", textoKey: "exercises:spanish.acc.q4.r3" },
    ],
    respuestaCorrecta: ["l1:r3", "l2:r1", "l3:r2"],
    imprimible: true,
  },
  {
    id: "len-3-acc-005",
    materia: "lengua",
    tema: "spelling.accents",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:spanish.acc.q5.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "len-3-acc-006",
    materia: "lengua",
    tema: "spelling.accents",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.acc.q6.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.acc.q6.a" },
      { id: "b", textoKey: "exercises:spanish.acc.q6.b" },
      { id: "c", textoKey: "exercises:spanish.acc.q6.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "len-3-acc-007",
    materia: "lengua",
    tema: "spelling.accents",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.acc.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.acc.q7.a" },
      { id: "b", textoKey: "exercises:spanish.acc.q7.b" },
      { id: "c", textoKey: "exercises:spanish.acc.q7.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "len-3-acc-008",
    materia: "lengua",
    tema: "spelling.accents",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:spanish.acc.q8.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },

  // ─── Signos de puntuación ─────────────────────────────────────────────────
  {
    id: "len-3-pun-001",
    materia: "lengua",
    tema: "punctuation",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.pun.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.pun.q1.a" },
      { id: "b", textoKey: "exercises:spanish.pun.q1.b" },
      { id: "c", textoKey: "exercises:spanish.pun.q1.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "len-3-pun-002",
    materia: "lengua",
    tema: "punctuation",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:spanish.pun.q2.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "len-3-pun-003",
    materia: "lengua",
    tema: "punctuation",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.pun.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.pun.q3.a" },
      { id: "b", textoKey: "exercises:spanish.pun.q3.b" },
      { id: "c", textoKey: "exercises:spanish.pun.q3.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "len-3-pun-004",
    materia: "lengua",
    tema: "punctuation",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:spanish.pun.q4.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "len-3-pun-005",
    materia: "lengua",
    tema: "punctuation",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:spanish.pun.q5.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:spanish.pun.q5.l1" },
      { id: "l2", textoKey: "exercises:spanish.pun.q5.l2" },
      { id: "l3", textoKey: "exercises:spanish.pun.q5.l3" },
      { id: "r1", textoKey: "exercises:spanish.pun.q5.r1" },
      { id: "r2", textoKey: "exercises:spanish.pun.q5.r2" },
      { id: "r3", textoKey: "exercises:spanish.pun.q5.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r3", "l3:r1"],
    imprimible: true,
  },
  {
    id: "len-3-pun-006",
    materia: "lengua",
    tema: "punctuation",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.pun.q6.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.pun.q6.a" },
      { id: "b", textoKey: "exercises:spanish.pun.q6.b" },
      { id: "c", textoKey: "exercises:spanish.pun.q6.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "len-3-pun-007",
    materia: "lengua",
    tema: "punctuation",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:spanish.pun.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:spanish.pun.q7.a" },
      { id: "b", textoKey: "exercises:spanish.pun.q7.b" },
      { id: "c", textoKey: "exercises:spanish.pun.q7.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "len-3-pun-008",
    materia: "lengua",
    tema: "punctuation",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:spanish.pun.q8.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
];
