/*
 * Contenido real de Matemáticas.
 * Mates sigue el idioma de la UI (las claves i18n viven en EN y ES).
 * Los ejercicios de cálculo son GENERADOS (D-6): operandos aleatorios por
 * repetición, respuesta calculada. Los de numeración son estáticos.
 */
import type { EjercicioAny } from "../types";

const tf = (id: string, tema: string, q: string, ans: "true" | "false"): EjercicioAny => ({
  id, materia: "matematicas", tema, nivel: "3", tipo: "verdadero-falso",
  enunciadoKey: q,
  opciones: [
    { id: "true", textoKey: "quiz:answer.trueLabel" },
    { id: "false", textoKey: "quiz:answer.falseLabel" },
  ],
  respuestaCorrecta: ans,
  imprimible: true,
});

const mc = (id: string, tema: string, q: string, ans: "a" | "b" | "c", sec: string, n: string): EjercicioAny => ({
  id, materia: "matematicas", tema, nivel: "3", tipo: "opcion-multiple",
  enunciadoKey: q,
  opciones: [
    { id: "a", textoKey: `exercises:math.${sec}.${n}.a` },
    { id: "b", textoKey: `exercises:math.${sec}.${n}.b` },
    { id: "c", textoKey: `exercises:math.${sec}.${n}.c` },
  ],
  respuestaCorrecta: ans,
  imprimible: true,
});

export const matematicas: EjercicioAny[] = [
  // --- Sumas con llevadas (generado) ---
  { id: "mat-3-add-gen", materia: "matematicas", tema: "operations.add_carry", nivel: "3", tipo: "respuesta-corta", operacion: "add", plantillaKey: "exercises:math.template.operation", imprimible: true },
  // --- Tablas de multiplicar (generado) ---
  { id: "mat-3-times-gen", materia: "matematicas", tema: "operations.times_tables", nivel: "3", tipo: "respuesta-corta", operacion: "times-tables", plantillaKey: "exercises:math.template.operation", imprimible: true },
  // --- División exacta (generado) ---
  { id: "mat-3-div-gen", materia: "matematicas", tema: "operations.division_intro", nivel: "3", tipo: "respuesta-corta", operacion: "division-exact", plantillaKey: "exercises:math.template.operation", imprimible: true },

  // ─── Pares e impares (q1-q32) ─────────────────────────────────────────────
  tf("mat-3-evenodd-001","numbers.even_odd","exercises:math.evenodd.q1.prompt","true"),
  tf("mat-3-evenodd-002","numbers.even_odd","exercises:math.evenodd.q2.prompt","false"),
  mc("mat-3-evenodd-003","numbers.even_odd","exercises:math.evenodd.q3.prompt","b","evenodd","q3"),
  tf("mat-3-evenodd-004","numbers.even_odd","exercises:math.evenodd.q4.prompt","false"),
  mc("mat-3-evenodd-005","numbers.even_odd","exercises:math.evenodd.q5.prompt","b","evenodd","q5"),
  tf("mat-3-evenodd-006","numbers.even_odd","exercises:math.evenodd.q6.prompt","true"),
  mc("mat-3-evenodd-007","numbers.even_odd","exercises:math.evenodd.q7.prompt","b","evenodd","q7"),
  mc("mat-3-evenodd-008","numbers.even_odd","exercises:math.evenodd.q8.prompt","c","evenodd","q8"),
  tf("mat-3-evenodd-009","numbers.even_odd","exercises:math.evenodd.q9.prompt","true"),
  tf("mat-3-evenodd-010","numbers.even_odd","exercises:math.evenodd.q10.prompt","true"),
  mc("mat-3-evenodd-011","numbers.even_odd","exercises:math.evenodd.q11.prompt","c","evenodd","q11"),
  tf("mat-3-evenodd-012","numbers.even_odd","exercises:math.evenodd.q12.prompt","false"),
  mc("mat-3-evenodd-013","numbers.even_odd","exercises:math.evenodd.q13.prompt","b","evenodd","q13"),
  tf("mat-3-evenodd-014","numbers.even_odd","exercises:math.evenodd.q14.prompt","false"),
  mc("mat-3-evenodd-015","numbers.even_odd","exercises:math.evenodd.q15.prompt","b","evenodd","q15"),
  tf("mat-3-evenodd-016","numbers.even_odd","exercises:math.evenodd.q16.prompt","true"),
  mc("mat-3-evenodd-017","numbers.even_odd","exercises:math.evenodd.q17.prompt","c","evenodd","q17"),
  tf("mat-3-evenodd-018","numbers.even_odd","exercises:math.evenodd.q18.prompt","true"),
  mc("mat-3-evenodd-019","numbers.even_odd","exercises:math.evenodd.q19.prompt","c","evenodd","q19"),
  tf("mat-3-evenodd-020","numbers.even_odd","exercises:math.evenodd.q20.prompt","true"),
  mc("mat-3-evenodd-021","numbers.even_odd","exercises:math.evenodd.q21.prompt","c","evenodd","q21"),
  tf("mat-3-evenodd-022","numbers.even_odd","exercises:math.evenodd.q22.prompt","false"),
  mc("mat-3-evenodd-023","numbers.even_odd","exercises:math.evenodd.q23.prompt","a","evenodd","q23"),
  tf("mat-3-evenodd-024","numbers.even_odd","exercises:math.evenodd.q24.prompt","true"),
  mc("mat-3-evenodd-025","numbers.even_odd","exercises:math.evenodd.q25.prompt","b","evenodd","q25"),
  tf("mat-3-evenodd-026","numbers.even_odd","exercises:math.evenodd.q26.prompt","false"),
  mc("mat-3-evenodd-027","numbers.even_odd","exercises:math.evenodd.q27.prompt","c","evenodd","q27"),
  tf("mat-3-evenodd-028","numbers.even_odd","exercises:math.evenodd.q28.prompt","true"),
  mc("mat-3-evenodd-029","numbers.even_odd","exercises:math.evenodd.q29.prompt","b","evenodd","q29"),
  tf("mat-3-evenodd-030","numbers.even_odd","exercises:math.evenodd.q30.prompt","true"),
  mc("mat-3-evenodd-031","numbers.even_odd","exercises:math.evenodd.q31.prompt","c","evenodd","q31"),
  tf("mat-3-evenodd-032","numbers.even_odd","exercises:math.evenodd.q32.prompt","true"),

  // ─── Valor posicional (q1-q32) ────────────────────────────────────────────
  tf("mat-3-pv-001","numbers.place_value","exercises:math.placevalue.q1.prompt","true"),
  tf("mat-3-pv-002","numbers.place_value","exercises:math.placevalue.q2.prompt","false"),
  mc("mat-3-pv-003","numbers.place_value","exercises:math.placevalue.q3.prompt","b","placevalue","q3"),
  tf("mat-3-pv-004","numbers.place_value","exercises:math.placevalue.q4.prompt","true"),
  mc("mat-3-pv-005","numbers.place_value","exercises:math.placevalue.q5.prompt","a","placevalue","q5"),
  tf("mat-3-pv-006","numbers.place_value","exercises:math.placevalue.q6.prompt","true"),
  mc("mat-3-pv-007","numbers.place_value","exercises:math.placevalue.q7.prompt","a","placevalue","q7"),
  tf("mat-3-pv-008","numbers.place_value","exercises:math.placevalue.q8.prompt","false"),
  mc("mat-3-pv-009","numbers.place_value","exercises:math.placevalue.q9.prompt","c","placevalue","q9"),
  tf("mat-3-pv-010","numbers.place_value","exercises:math.placevalue.q10.prompt","true"),
  mc("mat-3-pv-011","numbers.place_value","exercises:math.placevalue.q11.prompt","c","placevalue","q11"),
  tf("mat-3-pv-012","numbers.place_value","exercises:math.placevalue.q12.prompt","true"),
  mc("mat-3-pv-013","numbers.place_value","exercises:math.placevalue.q13.prompt","b","placevalue","q13"),
  tf("mat-3-pv-014","numbers.place_value","exercises:math.placevalue.q14.prompt","false"),
  mc("mat-3-pv-015","numbers.place_value","exercises:math.placevalue.q15.prompt","c","placevalue","q15"),
  tf("mat-3-pv-016","numbers.place_value","exercises:math.placevalue.q16.prompt","true"),
  mc("mat-3-pv-017","numbers.place_value","exercises:math.placevalue.q17.prompt","c","placevalue","q17"),
  tf("mat-3-pv-018","numbers.place_value","exercises:math.placevalue.q18.prompt","false"),
  mc("mat-3-pv-019","numbers.place_value","exercises:math.placevalue.q19.prompt","a","placevalue","q19"),
  tf("mat-3-pv-020","numbers.place_value","exercises:math.placevalue.q20.prompt","true"),
  mc("mat-3-pv-021","numbers.place_value","exercises:math.placevalue.q21.prompt","b","placevalue","q21"),
  tf("mat-3-pv-022","numbers.place_value","exercises:math.placevalue.q22.prompt","false"),
  mc("mat-3-pv-023","numbers.place_value","exercises:math.placevalue.q23.prompt","b","placevalue","q23"),
  tf("mat-3-pv-024","numbers.place_value","exercises:math.placevalue.q24.prompt","true"),
  mc("mat-3-pv-025","numbers.place_value","exercises:math.placevalue.q25.prompt","b","placevalue","q25"),
  tf("mat-3-pv-026","numbers.place_value","exercises:math.placevalue.q26.prompt","false"),
  mc("mat-3-pv-027","numbers.place_value","exercises:math.placevalue.q27.prompt","c","placevalue","q27"),
  tf("mat-3-pv-028","numbers.place_value","exercises:math.placevalue.q28.prompt","false"),
  mc("mat-3-pv-029","numbers.place_value","exercises:math.placevalue.q29.prompt","b","placevalue","q29"),
  tf("mat-3-pv-030","numbers.place_value","exercises:math.placevalue.q30.prompt","false"),
  mc("mat-3-pv-031","numbers.place_value","exercises:math.placevalue.q31.prompt","b","placevalue","q31"),
  tf("mat-3-pv-032","numbers.place_value","exercises:math.placevalue.q32.prompt","true"),

  // ─── Comparar y ordenar (q1-q32) ──────────────────────────────────────────
  tf("mat-3-ord-001","numbers.ordering","exercises:math.ordering.q1.prompt","false"),
  tf("mat-3-ord-002","numbers.ordering","exercises:math.ordering.q2.prompt","true"),
  mc("mat-3-ord-003","numbers.ordering","exercises:math.ordering.q3.prompt","b","ordering","q3"),
  tf("mat-3-ord-004","numbers.ordering","exercises:math.ordering.q4.prompt","true"),
  mc("mat-3-ord-005","numbers.ordering","exercises:math.ordering.q5.prompt","c","ordering","q5"),
  tf("mat-3-ord-006","numbers.ordering","exercises:math.ordering.q6.prompt","false"),
  mc("mat-3-ord-007","numbers.ordering","exercises:math.ordering.q7.prompt","b","ordering","q7"),
  tf("mat-3-ord-008","numbers.ordering","exercises:math.ordering.q8.prompt","true"),
  mc("mat-3-ord-009","numbers.ordering","exercises:math.ordering.q9.prompt","a","ordering","q9"),
  tf("mat-3-ord-010","numbers.ordering","exercises:math.ordering.q10.prompt","true"),
  mc("mat-3-ord-011","numbers.ordering","exercises:math.ordering.q11.prompt","b","ordering","q11"),
  tf("mat-3-ord-012","numbers.ordering","exercises:math.ordering.q12.prompt","true"),
  mc("mat-3-ord-013","numbers.ordering","exercises:math.ordering.q13.prompt","b","ordering","q13"),
  tf("mat-3-ord-014","numbers.ordering","exercises:math.ordering.q14.prompt","true"),
  mc("mat-3-ord-015","numbers.ordering","exercises:math.ordering.q15.prompt","c","ordering","q15"),
  tf("mat-3-ord-016","numbers.ordering","exercises:math.ordering.q16.prompt","true"),
  mc("mat-3-ord-017","numbers.ordering","exercises:math.ordering.q17.prompt","b","ordering","q17"),
  tf("mat-3-ord-018","numbers.ordering","exercises:math.ordering.q18.prompt","false"),
  mc("mat-3-ord-019","numbers.ordering","exercises:math.ordering.q19.prompt","a","ordering","q19"),
  tf("mat-3-ord-020","numbers.ordering","exercises:math.ordering.q20.prompt","true"),
  mc("mat-3-ord-021","numbers.ordering","exercises:math.ordering.q21.prompt","b","ordering","q21"),
  tf("mat-3-ord-022","numbers.ordering","exercises:math.ordering.q22.prompt","true"),
  mc("mat-3-ord-023","numbers.ordering","exercises:math.ordering.q23.prompt","b","ordering","q23"),
  tf("mat-3-ord-024","numbers.ordering","exercises:math.ordering.q24.prompt","true"),
  mc("mat-3-ord-025","numbers.ordering","exercises:math.ordering.q25.prompt","c","ordering","q25"),
  tf("mat-3-ord-026","numbers.ordering","exercises:math.ordering.q26.prompt","true"),
  mc("mat-3-ord-027","numbers.ordering","exercises:math.ordering.q27.prompt","b","ordering","q27"),
  tf("mat-3-ord-028","numbers.ordering","exercises:math.ordering.q28.prompt","true"),
  mc("mat-3-ord-029","numbers.ordering","exercises:math.ordering.q29.prompt","a","ordering","q29"),
  tf("mat-3-ord-030","numbers.ordering","exercises:math.ordering.q30.prompt","true"),
  mc("mat-3-ord-031","numbers.ordering","exercises:math.ordering.q31.prompt","b","ordering","q31"),
  tf("mat-3-ord-032","numbers.ordering","exercises:math.ordering.q32.prompt","true"),

  // ─── Redondeo (q1-q32) ────────────────────────────────────────────────────
  tf("mat-3-round-001","numbers.rounding","exercises:math.rounding.q1.prompt","true"),
  tf("mat-3-round-002","numbers.rounding","exercises:math.rounding.q2.prompt","false"),
  mc("mat-3-round-003","numbers.rounding","exercises:math.rounding.q3.prompt","c","rounding","q3"),
  tf("mat-3-round-004","numbers.rounding","exercises:math.rounding.q4.prompt","true"),
  mc("mat-3-round-005","numbers.rounding","exercises:math.rounding.q5.prompt","c","rounding","q5"),
  tf("mat-3-round-006","numbers.rounding","exercises:math.rounding.q6.prompt","false"),
  mc("mat-3-round-007","numbers.rounding","exercises:math.rounding.q7.prompt","c","rounding","q7"),
  tf("mat-3-round-008","numbers.rounding","exercises:math.rounding.q8.prompt","true"),
  mc("mat-3-round-009","numbers.rounding","exercises:math.rounding.q9.prompt","a","rounding","q9"),
  tf("mat-3-round-010","numbers.rounding","exercises:math.rounding.q10.prompt","true"),
  mc("mat-3-round-011","numbers.rounding","exercises:math.rounding.q11.prompt","c","rounding","q11"),
  tf("mat-3-round-012","numbers.rounding","exercises:math.rounding.q12.prompt","true"),
  mc("mat-3-round-013","numbers.rounding","exercises:math.rounding.q13.prompt","c","rounding","q13"),
  tf("mat-3-round-014","numbers.rounding","exercises:math.rounding.q14.prompt","true"),
  mc("mat-3-round-015","numbers.rounding","exercises:math.rounding.q15.prompt","a","rounding","q15"),
  tf("mat-3-round-016","numbers.rounding","exercises:math.rounding.q16.prompt","true"),
  mc("mat-3-round-017","numbers.rounding","exercises:math.rounding.q17.prompt","b","rounding","q17"),
  tf("mat-3-round-018","numbers.rounding","exercises:math.rounding.q18.prompt","true"),
  mc("mat-3-round-019","numbers.rounding","exercises:math.rounding.q19.prompt","c","rounding","q19"),
  tf("mat-3-round-020","numbers.rounding","exercises:math.rounding.q20.prompt","false"),
  mc("mat-3-round-021","numbers.rounding","exercises:math.rounding.q21.prompt","c","rounding","q21"),
  tf("mat-3-round-022","numbers.rounding","exercises:math.rounding.q22.prompt","false"),
  mc("mat-3-round-023","numbers.rounding","exercises:math.rounding.q23.prompt","a","rounding","q23"),
  tf("mat-3-round-024","numbers.rounding","exercises:math.rounding.q24.prompt","true"),
  mc("mat-3-round-025","numbers.rounding","exercises:math.rounding.q25.prompt","b","rounding","q25"),
  tf("mat-3-round-026","numbers.rounding","exercises:math.rounding.q26.prompt","true"),
  mc("mat-3-round-027","numbers.rounding","exercises:math.rounding.q27.prompt","a","rounding","q27"),
  tf("mat-3-round-028","numbers.rounding","exercises:math.rounding.q28.prompt","true"),
  mc("mat-3-round-029","numbers.rounding","exercises:math.rounding.q29.prompt","c","rounding","q29"),
  tf("mat-3-round-030","numbers.rounding","exercises:math.rounding.q30.prompt","true"),
  mc("mat-3-round-031","numbers.rounding","exercises:math.rounding.q31.prompt","b","rounding","q31"),
  tf("mat-3-round-032","numbers.rounding","exercises:math.rounding.q32.prompt","true"),

  // ─── Figuras y geometría (q1-q32) ─────────────────────────────────────────
  tf("mat-3-geo-001","geometry.shapes","exercises:math.shapes.q1.prompt","true"),
  tf("mat-3-geo-002","geometry.shapes","exercises:math.shapes.q2.prompt","true"),
  mc("mat-3-geo-003","geometry.shapes","exercises:math.shapes.q3.prompt","b","shapes","q3"),
  tf("mat-3-geo-004","geometry.shapes","exercises:math.shapes.q4.prompt","false"),
  mc("mat-3-geo-005","geometry.shapes","exercises:math.shapes.q5.prompt","b","shapes","q5"),
  tf("mat-3-geo-006","geometry.shapes","exercises:math.shapes.q6.prompt","true"),
  mc("mat-3-geo-007","geometry.shapes","exercises:math.shapes.q7.prompt","b","shapes","q7"),
  tf("mat-3-geo-008","geometry.shapes","exercises:math.shapes.q8.prompt","true"),
  mc("mat-3-geo-009","geometry.shapes","exercises:math.shapes.q9.prompt","c","shapes","q9"),
  tf("mat-3-geo-010","geometry.shapes","exercises:math.shapes.q10.prompt","true"),
  mc("mat-3-geo-011","geometry.shapes","exercises:math.shapes.q11.prompt","c","shapes","q11"),
  tf("mat-3-geo-012","geometry.shapes","exercises:math.shapes.q12.prompt","true"),
  mc("mat-3-geo-013","geometry.shapes","exercises:math.shapes.q13.prompt","c","shapes","q13"),
  tf("mat-3-geo-014","geometry.shapes","exercises:math.shapes.q14.prompt","true"),
  mc("mat-3-geo-015","geometry.shapes","exercises:math.shapes.q15.prompt","b","shapes","q15"),
  tf("mat-3-geo-016","geometry.shapes","exercises:math.shapes.q16.prompt","true"),
  mc("mat-3-geo-017","geometry.shapes","exercises:math.shapes.q17.prompt","b","shapes","q17"),
  tf("mat-3-geo-018","geometry.shapes","exercises:math.shapes.q18.prompt","true"),
  mc("mat-3-geo-019","geometry.shapes","exercises:math.shapes.q19.prompt","c","shapes","q19"),
  tf("mat-3-geo-020","geometry.shapes","exercises:math.shapes.q20.prompt","true"),
  mc("mat-3-geo-021","geometry.shapes","exercises:math.shapes.q21.prompt","b","shapes","q21"),
  tf("mat-3-geo-022","geometry.shapes","exercises:math.shapes.q22.prompt","true"),
  mc("mat-3-geo-023","geometry.shapes","exercises:math.shapes.q23.prompt","b","shapes","q23"),
  tf("mat-3-geo-024","geometry.shapes","exercises:math.shapes.q24.prompt","true"),
  mc("mat-3-geo-025","geometry.shapes","exercises:math.shapes.q25.prompt","b","shapes","q25"),
  tf("mat-3-geo-026","geometry.shapes","exercises:math.shapes.q26.prompt","true"),
  mc("mat-3-geo-027","geometry.shapes","exercises:math.shapes.q27.prompt","c","shapes","q27"),
  tf("mat-3-geo-028","geometry.shapes","exercises:math.shapes.q28.prompt","true"),
  mc("mat-3-geo-029","geometry.shapes","exercises:math.shapes.q29.prompt","a","shapes","q29"),
  tf("mat-3-geo-030","geometry.shapes","exercises:math.shapes.q30.prompt","true"),
  mc("mat-3-geo-031","geometry.shapes","exercises:math.shapes.q31.prompt","b","shapes","q31"),
  tf("mat-3-geo-032","geometry.shapes","exercises:math.shapes.q32.prompt","true"),

  // ─── El tiempo (q1-q32) ───────────────────────────────────────────────────
  tf("mat-3-time-001","measurement.time","exercises:math.time.q1.prompt","true"),
  tf("mat-3-time-002","measurement.time","exercises:math.time.q2.prompt","true"),
  mc("mat-3-time-003","measurement.time","exercises:math.time.q3.prompt","b","time","q3"),
  tf("mat-3-time-004","measurement.time","exercises:math.time.q4.prompt","true"),
  mc("mat-3-time-005","measurement.time","exercises:math.time.q5.prompt","b","time","q5"),
  tf("mat-3-time-006","measurement.time","exercises:math.time.q6.prompt","false"),
  mc("mat-3-time-007","measurement.time","exercises:math.time.q7.prompt","b","time","q7"),
  tf("mat-3-time-008","measurement.time","exercises:math.time.q8.prompt","true"),
  mc("mat-3-time-009","measurement.time","exercises:math.time.q9.prompt","b","time","q9"),
  tf("mat-3-time-010","measurement.time","exercises:math.time.q10.prompt","true"),
  mc("mat-3-time-011","measurement.time","exercises:math.time.q11.prompt","b","time","q11"),
  tf("mat-3-time-012","measurement.time","exercises:math.time.q12.prompt","true"),
  mc("mat-3-time-013","measurement.time","exercises:math.time.q13.prompt","c","time","q13"),
  tf("mat-3-time-014","measurement.time","exercises:math.time.q14.prompt","true"),
  mc("mat-3-time-015","measurement.time","exercises:math.time.q15.prompt","c","time","q15"),
  tf("mat-3-time-016","measurement.time","exercises:math.time.q16.prompt","true"),
  mc("mat-3-time-017","measurement.time","exercises:math.time.q17.prompt","a","time","q17"),
  tf("mat-3-time-018","measurement.time","exercises:math.time.q18.prompt","true"),
  mc("mat-3-time-019","measurement.time","exercises:math.time.q19.prompt","c","time","q19"),
  tf("mat-3-time-020","measurement.time","exercises:math.time.q20.prompt","true"),
  mc("mat-3-time-021","measurement.time","exercises:math.time.q21.prompt","c","time","q21"),
  tf("mat-3-time-022","measurement.time","exercises:math.time.q22.prompt","true"),
  mc("mat-3-time-023","measurement.time","exercises:math.time.q23.prompt","b","time","q23"),
  tf("mat-3-time-024","measurement.time","exercises:math.time.q24.prompt","true"),
  mc("mat-3-time-025","measurement.time","exercises:math.time.q25.prompt","c","time","q25"),
  tf("mat-3-time-026","measurement.time","exercises:math.time.q26.prompt","true"),
  mc("mat-3-time-027","measurement.time","exercises:math.time.q27.prompt","b","time","q27"),
  tf("mat-3-time-028","measurement.time","exercises:math.time.q28.prompt","true"),
  mc("mat-3-time-029","measurement.time","exercises:math.time.q29.prompt","b","time","q29"),
  tf("mat-3-time-030","measurement.time","exercises:math.time.q30.prompt","true"),
  mc("mat-3-time-031","measurement.time","exercises:math.time.q31.prompt","b","time","q31"),
  tf("mat-3-time-032","measurement.time","exercises:math.time.q32.prompt","true"),

  // ─── Longitud y medida (q1-q32) ───────────────────────────────────────────
  tf("mat-3-len-001","measurement.length","exercises:math.length.q1.prompt","true"),
  tf("mat-3-len-002","measurement.length","exercises:math.length.q2.prompt","false"),
  mc("mat-3-len-003","measurement.length","exercises:math.length.q3.prompt","b","length","q3"),
  tf("mat-3-len-004","measurement.length","exercises:math.length.q4.prompt","true"),
  mc("mat-3-len-005","measurement.length","exercises:math.length.q5.prompt","c","length","q5"),
  tf("mat-3-len-006","measurement.length","exercises:math.length.q6.prompt","true"),
  mc("mat-3-len-007","measurement.length","exercises:math.length.q7.prompt","c","length","q7"),
  tf("mat-3-len-008","measurement.length","exercises:math.length.q8.prompt","true"),
  mc("mat-3-len-009","measurement.length","exercises:math.length.q9.prompt","b","length","q9"),
  tf("mat-3-len-010","measurement.length","exercises:math.length.q10.prompt","true"),
  mc("mat-3-len-011","measurement.length","exercises:math.length.q11.prompt","c","length","q11"),
  tf("mat-3-len-012","measurement.length","exercises:math.length.q12.prompt","true"),
  mc("mat-3-len-013","measurement.length","exercises:math.length.q13.prompt","b","length","q13"),
  tf("mat-3-len-014","measurement.length","exercises:math.length.q14.prompt","true"),
  mc("mat-3-len-015","measurement.length","exercises:math.length.q15.prompt","c","length","q15"),
  tf("mat-3-len-016","measurement.length","exercises:math.length.q16.prompt","true"),
  mc("mat-3-len-017","measurement.length","exercises:math.length.q17.prompt","b","length","q17"),
  tf("mat-3-len-018","measurement.length","exercises:math.length.q18.prompt","true"),
  mc("mat-3-len-019","measurement.length","exercises:math.length.q19.prompt","c","length","q19"),
  tf("mat-3-len-020","measurement.length","exercises:math.length.q20.prompt","true"),
  mc("mat-3-len-021","measurement.length","exercises:math.length.q21.prompt","b","length","q21"),
  tf("mat-3-len-022","measurement.length","exercises:math.length.q22.prompt","true"),
  mc("mat-3-len-023","measurement.length","exercises:math.length.q23.prompt","a","length","q23"),
  tf("mat-3-len-024","measurement.length","exercises:math.length.q24.prompt","true"),
  mc("mat-3-len-025","measurement.length","exercises:math.length.q25.prompt","a","length","q25"),
  tf("mat-3-len-026","measurement.length","exercises:math.length.q26.prompt","false"),
  mc("mat-3-len-027","measurement.length","exercises:math.length.q27.prompt","a","length","q27"),
  tf("mat-3-len-028","measurement.length","exercises:math.length.q28.prompt","false"),
  mc("mat-3-len-029","measurement.length","exercises:math.length.q29.prompt","b","length","q29"),
  tf("mat-3-len-030","measurement.length","exercises:math.length.q30.prompt","true"),
  mc("mat-3-len-031","measurement.length","exercises:math.length.q31.prompt","b","length","q31"),
  tf("mat-3-len-032","measurement.length","exercises:math.length.q32.prompt","true"),

  // ─── Fracciones (q1-q32) ──────────────────────────────────────────────────
  tf("mat-3-frac-001","numbers.fractions","exercises:math.fractions.q1.prompt","true"),
  tf("mat-3-frac-002","numbers.fractions","exercises:math.fractions.q2.prompt","true"),
  mc("mat-3-frac-003","numbers.fractions","exercises:math.fractions.q3.prompt","b","fractions","q3"),
  tf("mat-3-frac-004","numbers.fractions","exercises:math.fractions.q4.prompt","true"),
  mc("mat-3-frac-005","numbers.fractions","exercises:math.fractions.q5.prompt","c","fractions","q5"),
  tf("mat-3-frac-006","numbers.fractions","exercises:math.fractions.q6.prompt","true"),
  mc("mat-3-frac-007","numbers.fractions","exercises:math.fractions.q7.prompt","b","fractions","q7"),
  tf("mat-3-frac-008","numbers.fractions","exercises:math.fractions.q8.prompt","false"),
  mc("mat-3-frac-009","numbers.fractions","exercises:math.fractions.q9.prompt","a","fractions","q9"),
  tf("mat-3-frac-010","numbers.fractions","exercises:math.fractions.q10.prompt","true"),
  mc("mat-3-frac-011","numbers.fractions","exercises:math.fractions.q11.prompt","c","fractions","q11"),
  tf("mat-3-frac-012","numbers.fractions","exercises:math.fractions.q12.prompt","true"),
  mc("mat-3-frac-013","numbers.fractions","exercises:math.fractions.q13.prompt","c","fractions","q13"),
  tf("mat-3-frac-014","numbers.fractions","exercises:math.fractions.q14.prompt","true"),
  mc("mat-3-frac-015","numbers.fractions","exercises:math.fractions.q15.prompt","b","fractions","q15"),
  tf("mat-3-frac-016","numbers.fractions","exercises:math.fractions.q16.prompt","true"),
  mc("mat-3-frac-017","numbers.fractions","exercises:math.fractions.q17.prompt","b","fractions","q17"),
  tf("mat-3-frac-018","numbers.fractions","exercises:math.fractions.q18.prompt","true"),
  mc("mat-3-frac-019","numbers.fractions","exercises:math.fractions.q19.prompt","b","fractions","q19"),
  tf("mat-3-frac-020","numbers.fractions","exercises:math.fractions.q20.prompt","true"),
  mc("mat-3-frac-021","numbers.fractions","exercises:math.fractions.q21.prompt","c","fractions","q21"),
  tf("mat-3-frac-022","numbers.fractions","exercises:math.fractions.q22.prompt","false"),
  mc("mat-3-frac-023","numbers.fractions","exercises:math.fractions.q23.prompt","c","fractions","q23"),
  tf("mat-3-frac-024","numbers.fractions","exercises:math.fractions.q24.prompt","true"),
  mc("mat-3-frac-025","numbers.fractions","exercises:math.fractions.q25.prompt","b","fractions","q25"),
  tf("mat-3-frac-026","numbers.fractions","exercises:math.fractions.q26.prompt","true"),
  mc("mat-3-frac-027","numbers.fractions","exercises:math.fractions.q27.prompt","b","fractions","q27"),
  tf("mat-3-frac-028","numbers.fractions","exercises:math.fractions.q28.prompt","true"),
  mc("mat-3-frac-029","numbers.fractions","exercises:math.fractions.q29.prompt","b","fractions","q29"),
  tf("mat-3-frac-030","numbers.fractions","exercises:math.fractions.q30.prompt","false"),
  mc("mat-3-frac-031","numbers.fractions","exercises:math.fractions.q31.prompt","b","fractions","q31"),
  tf("mat-3-frac-032","numbers.fractions","exercises:math.fractions.q32.prompt","true"),
];
