/*
 * Contenido real de Ciencias Sociales.
 * Sigue el idioma de la UI: las claves i18n viven en EN y ES.
 * Contenido original.
 */
import type { EjercicioAny } from "../types";

export const sociales: EjercicioAny[] = [

  // ─── El universo y el Sistema Solar ──────────────────────────────────────
  {
    id: "soc-3-universe-001",
    materia: "sociales",
    tema: "earth_universe.universe",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.universe.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.universe.q1.a" },
      { id: "b", textoKey: "exercises:social.universe.q1.b" },
      { id: "c", textoKey: "exercises:social.universe.q1.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "soc-3-universe-002",
    materia: "sociales",
    tema: "earth_universe.universe",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.universe.q2.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "soc-3-universe-003",
    materia: "sociales",
    tema: "earth_universe.universe",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.universe.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.universe.q3.a" },
      { id: "b", textoKey: "exercises:social.universe.q3.b" },
      { id: "c", textoKey: "exercises:social.universe.q3.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "soc-3-universe-004",
    materia: "sociales",
    tema: "earth_universe.universe",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.universe.q4.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.universe.q4.a" },
      { id: "b", textoKey: "exercises:social.universe.q4.b" },
      { id: "c", textoKey: "exercises:social.universe.q4.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-universe-005",
    materia: "sociales",
    tema: "earth_universe.universe",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.universe.q5.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "soc-3-universe-006",
    materia: "sociales",
    tema: "earth_universe.universe",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.universe.q6.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.universe.q6.a" },
      { id: "b", textoKey: "exercises:social.universe.q6.b" },
      { id: "c", textoKey: "exercises:social.universe.q6.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "soc-3-universe-007",
    materia: "sociales",
    tema: "earth_universe.universe",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:social.universe.q7.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:social.universe.q7.l1" },
      { id: "l2", textoKey: "exercises:social.universe.q7.l2" },
      { id: "l3", textoKey: "exercises:social.universe.q7.l3" },
      { id: "r1", textoKey: "exercises:social.universe.q7.r1" },
      { id: "r2", textoKey: "exercises:social.universe.q7.r2" },
      { id: "r3", textoKey: "exercises:social.universe.q7.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r3", "l3:r1"],
    imprimible: true,
  },
  {
    id: "soc-3-universe-008",
    materia: "sociales",
    tema: "earth_universe.universe",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.universe.q8.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },

  // ─── Mapas y puntos cardinales ────────────────────────────────────────────
  {
    id: "soc-3-maps-001",
    materia: "sociales",
    tema: "landscape.maps",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.maps.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.maps.q1.a" },
      { id: "b", textoKey: "exercises:social.maps.q1.b" },
      { id: "c", textoKey: "exercises:social.maps.q1.c" },
      { id: "d", textoKey: "exercises:social.maps.q1.d" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-maps-002",
    materia: "sociales",
    tema: "landscape.maps",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:social.maps.q2.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:social.maps.q2.l1" },
      { id: "l2", textoKey: "exercises:social.maps.q2.l2" },
      { id: "r1", textoKey: "exercises:social.maps.q2.r1" },
      { id: "r2", textoKey: "exercises:social.maps.q2.r2" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r1"],
    imprimible: true,
  },
  {
    id: "soc-3-maps-003",
    materia: "sociales",
    tema: "landscape.maps",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.maps.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.maps.q3.a" },
      { id: "b", textoKey: "exercises:social.maps.q3.b" },
      { id: "c", textoKey: "exercises:social.maps.q3.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "soc-3-maps-004",
    materia: "sociales",
    tema: "landscape.maps",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.maps.q4.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "soc-3-maps-005",
    materia: "sociales",
    tema: "landscape.maps",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.maps.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.maps.q5.a" },
      { id: "b", textoKey: "exercises:social.maps.q5.b" },
      { id: "c", textoKey: "exercises:social.maps.q5.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-maps-006",
    materia: "sociales",
    tema: "landscape.maps",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.maps.q6.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "soc-3-maps-007",
    materia: "sociales",
    tema: "landscape.maps",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.maps.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.maps.q7.a" },
      { id: "b", textoKey: "exercises:social.maps.q7.b" },
      { id: "c", textoKey: "exercises:social.maps.q7.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "soc-3-maps-008",
    materia: "sociales",
    tema: "landscape.maps",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:social.maps.q8.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:social.maps.q8.l1" },
      { id: "l2", textoKey: "exercises:social.maps.q8.l2" },
      { id: "l3", textoKey: "exercises:social.maps.q8.l3" },
      { id: "r1", textoKey: "exercises:social.maps.q8.r1" },
      { id: "r2", textoKey: "exercises:social.maps.q8.r2" },
      { id: "r3", textoKey: "exercises:social.maps.q8.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r3", "l3:r1"],
    imprimible: true,
  },

  // ─── España: relieve, ríos y comunidades autónomas ────────────────────────
  {
    id: "soc-3-spain-001",
    materia: "sociales",
    tema: "landscape.spain",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.spain.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.spain.q1.a" },
      { id: "b", textoKey: "exercises:social.spain.q1.b" },
      { id: "c", textoKey: "exercises:social.spain.q1.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-spain-002",
    materia: "sociales",
    tema: "landscape.spain",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.spain.q2.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "soc-3-spain-003",
    materia: "sociales",
    tema: "landscape.spain",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.spain.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.spain.q3.a" },
      { id: "b", textoKey: "exercises:social.spain.q3.b" },
      { id: "c", textoKey: "exercises:social.spain.q3.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-spain-004",
    materia: "sociales",
    tema: "landscape.spain",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.spain.q4.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "soc-3-spain-005",
    materia: "sociales",
    tema: "landscape.spain",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.spain.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.spain.q5.a" },
      { id: "b", textoKey: "exercises:social.spain.q5.b" },
      { id: "c", textoKey: "exercises:social.spain.q5.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-spain-006",
    materia: "sociales",
    tema: "landscape.spain",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:social.spain.q6.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:social.spain.q6.l1" },
      { id: "l2", textoKey: "exercises:social.spain.q6.l2" },
      { id: "l3", textoKey: "exercises:social.spain.q6.l3" },
      { id: "r1", textoKey: "exercises:social.spain.q6.r1" },
      { id: "r2", textoKey: "exercises:social.spain.q6.r2" },
      { id: "r3", textoKey: "exercises:social.spain.q6.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r3", "l3:r1"],
    imprimible: true,
  },
  {
    id: "soc-3-spain-007",
    materia: "sociales",
    tema: "landscape.spain",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.spain.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.spain.q7.a" },
      { id: "b", textoKey: "exercises:social.spain.q7.b" },
      { id: "c", textoKey: "exercises:social.spain.q7.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "soc-3-spain-008",
    materia: "sociales",
    tema: "landscape.spain",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.spain.q8.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },

  // ─── La población y el trabajo ────────────────────────────────────────────
  {
    id: "soc-3-pop-001",
    materia: "sociales",
    tema: "society.population",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.pop.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.pop.q1.a" },
      { id: "b", textoKey: "exercises:social.pop.q1.b" },
      { id: "c", textoKey: "exercises:social.pop.q1.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-pop-002",
    materia: "sociales",
    tema: "society.population",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.pop.q2.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "soc-3-pop-003",
    materia: "sociales",
    tema: "society.population",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.pop.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.pop.q3.a" },
      { id: "b", textoKey: "exercises:social.pop.q3.b" },
      { id: "c", textoKey: "exercises:social.pop.q3.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "soc-3-pop-004",
    materia: "sociales",
    tema: "society.population",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.pop.q4.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "soc-3-pop-005",
    materia: "sociales",
    tema: "society.population",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.pop.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.pop.q5.a" },
      { id: "b", textoKey: "exercises:social.pop.q5.b" },
      { id: "c", textoKey: "exercises:social.pop.q5.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-pop-006",
    materia: "sociales",
    tema: "society.population",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:social.pop.q6.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:social.pop.q6.l1" },
      { id: "l2", textoKey: "exercises:social.pop.q6.l2" },
      { id: "l3", textoKey: "exercises:social.pop.q6.l3" },
      { id: "r1", textoKey: "exercises:social.pop.q6.r1" },
      { id: "r2", textoKey: "exercises:social.pop.q6.r2" },
      { id: "r3", textoKey: "exercises:social.pop.q6.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r3", "l3:r1"],
    imprimible: true,
  },
  {
    id: "soc-3-pop-007",
    materia: "sociales",
    tema: "society.population",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.pop.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.pop.q7.a" },
      { id: "b", textoKey: "exercises:social.pop.q7.b" },
      { id: "c", textoKey: "exercises:social.pop.q7.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-pop-008",
    materia: "sociales",
    tema: "society.population",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.pop.q8.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },

  // ─── El tiempo histórico ──────────────────────────────────────────────────
  {
    id: "soc-3-time-001",
    materia: "sociales",
    tema: "history.time",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.time.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.time.q1.a" },
      { id: "b", textoKey: "exercises:social.time.q1.b" },
      { id: "c", textoKey: "exercises:social.time.q1.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-time-002",
    materia: "sociales",
    tema: "history.time",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.time.q2.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "soc-3-time-003",
    materia: "sociales",
    tema: "history.time",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.time.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.time.q3.a" },
      { id: "b", textoKey: "exercises:social.time.q3.b" },
      { id: "c", textoKey: "exercises:social.time.q3.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-time-004",
    materia: "sociales",
    tema: "history.time",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.time.q4.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "soc-3-time-005",
    materia: "sociales",
    tema: "history.time",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.time.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.time.q5.a" },
      { id: "b", textoKey: "exercises:social.time.q5.b" },
      { id: "c", textoKey: "exercises:social.time.q5.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "soc-3-time-006",
    materia: "sociales",
    tema: "history.time",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:social.time.q6.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:social.time.q6.l1" },
      { id: "l2", textoKey: "exercises:social.time.q6.l2" },
      { id: "l3", textoKey: "exercises:social.time.q6.l3" },
      { id: "r1", textoKey: "exercises:social.time.q6.r1" },
      { id: "r2", textoKey: "exercises:social.time.q6.r2" },
      { id: "r3", textoKey: "exercises:social.time.q6.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r3", "l3:r1"],
    imprimible: true,
  },
  {
    id: "soc-3-time-007",
    materia: "sociales",
    tema: "history.time",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.time.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.time.q7.a" },
      { id: "b", textoKey: "exercises:social.time.q7.b" },
      { id: "c", textoKey: "exercises:social.time.q7.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-time-008",
    materia: "sociales",
    tema: "history.time",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.time.q8.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
];
