/*
 * Contenido real de Ciencias Sociales.
 * Sigue el idioma de la UI: las claves i18n viven en EN y ES.
 * Contenido original.
 */
import type { EjercicioAny } from "../types";

const tfS = (id: string, tema: string, q: string, ans: "true" | "false"): EjercicioAny => ({
  id, materia: "sociales", tema, nivel: "3", tipo: "verdadero-falso",
  enunciadoKey: q,
  opciones: [
    { id: "true",  textoKey: "quiz:answer.trueLabel" },
    { id: "false", textoKey: "quiz:answer.falseLabel" },
  ],
  respuestaCorrecta: ans,
  imprimible: true,
});

const mcS = (id: string, tema: string, q: string, ans: "a" | "b" | "c", sec: string, n: string): EjercicioAny => ({
  id, materia: "sociales", tema, nivel: "3", tipo: "opcion-multiple",
  enunciadoKey: q,
  opciones: [
    { id: "a", textoKey: `exercises:social.${sec}.${n}.a` },
    { id: "b", textoKey: `exercises:social.${sec}.${n}.b` },
    { id: "c", textoKey: `exercises:social.${sec}.${n}.c` },
  ],
  respuestaCorrecta: ans,
  imprimible: true,
});

export const sociales: EjercicioAny[] = [

  // ─── El universo y el Sistema Solar ──────────────────────────────────────
  {
    id: "soc-3-universe-001",
    materia: "sociales",
    tema: "earth_universe.universe",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.universe.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.universe.q1.a" },
      { id: "b", textoKey: "exercises:social.universe.q1.b" },
      { id: "c", textoKey: "exercises:social.universe.q1.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "soc-3-universe-002",
    materia: "sociales",
    tema: "earth_universe.universe",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.universe.q2.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "soc-3-universe-003",
    materia: "sociales",
    tema: "earth_universe.universe",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.universe.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.universe.q3.a" },
      { id: "b", textoKey: "exercises:social.universe.q3.b" },
      { id: "c", textoKey: "exercises:social.universe.q3.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "soc-3-universe-004",
    materia: "sociales",
    tema: "earth_universe.universe",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.universe.q4.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.universe.q4.a" },
      { id: "b", textoKey: "exercises:social.universe.q4.b" },
      { id: "c", textoKey: "exercises:social.universe.q4.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-universe-005",
    materia: "sociales",
    tema: "earth_universe.universe",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.universe.q5.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "soc-3-universe-006",
    materia: "sociales",
    tema: "earth_universe.universe",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.universe.q6.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.universe.q6.a" },
      { id: "b", textoKey: "exercises:social.universe.q6.b" },
      { id: "c", textoKey: "exercises:social.universe.q6.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "soc-3-universe-007",
    materia: "sociales",
    tema: "earth_universe.universe",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:social.universe.q7.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:social.universe.q7.l1" },
      { id: "l2", textoKey: "exercises:social.universe.q7.l2" },
      { id: "l3", textoKey: "exercises:social.universe.q7.l3" },
      { id: "r1", textoKey: "exercises:social.universe.q7.r1" },
      { id: "r2", textoKey: "exercises:social.universe.q7.r2" },
      { id: "r3", textoKey: "exercises:social.universe.q7.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r3", "l3:r1"],
    imprimible: true,
  },
  {
    id: "soc-3-universe-008",
    materia: "sociales",
    tema: "earth_universe.universe",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.universe.q8.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },

  // ─── Mapas y puntos cardinales ────────────────────────────────────────────
  {
    id: "soc-3-maps-001",
    materia: "sociales",
    tema: "landscape.maps",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.maps.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.maps.q1.a" },
      { id: "b", textoKey: "exercises:social.maps.q1.b" },
      { id: "c", textoKey: "exercises:social.maps.q1.c" },
      { id: "d", textoKey: "exercises:social.maps.q1.d" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-maps-002",
    materia: "sociales",
    tema: "landscape.maps",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:social.maps.q2.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:social.maps.q2.l1" },
      { id: "l2", textoKey: "exercises:social.maps.q2.l2" },
      { id: "r1", textoKey: "exercises:social.maps.q2.r1" },
      { id: "r2", textoKey: "exercises:social.maps.q2.r2" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r1"],
    imprimible: true,
  },
  {
    id: "soc-3-maps-003",
    materia: "sociales",
    tema: "landscape.maps",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.maps.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.maps.q3.a" },
      { id: "b", textoKey: "exercises:social.maps.q3.b" },
      { id: "c", textoKey: "exercises:social.maps.q3.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "soc-3-maps-004",
    materia: "sociales",
    tema: "landscape.maps",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.maps.q4.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "soc-3-maps-005",
    materia: "sociales",
    tema: "landscape.maps",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.maps.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.maps.q5.a" },
      { id: "b", textoKey: "exercises:social.maps.q5.b" },
      { id: "c", textoKey: "exercises:social.maps.q5.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-maps-006",
    materia: "sociales",
    tema: "landscape.maps",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.maps.q6.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "soc-3-maps-007",
    materia: "sociales",
    tema: "landscape.maps",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.maps.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.maps.q7.a" },
      { id: "b", textoKey: "exercises:social.maps.q7.b" },
      { id: "c", textoKey: "exercises:social.maps.q7.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "soc-3-maps-008",
    materia: "sociales",
    tema: "landscape.maps",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:social.maps.q8.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:social.maps.q8.l1" },
      { id: "l2", textoKey: "exercises:social.maps.q8.l2" },
      { id: "l3", textoKey: "exercises:social.maps.q8.l3" },
      { id: "r1", textoKey: "exercises:social.maps.q8.r1" },
      { id: "r2", textoKey: "exercises:social.maps.q8.r2" },
      { id: "r3", textoKey: "exercises:social.maps.q8.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r3", "l3:r1"],
    imprimible: true,
  },

  // ─── España: relieve, ríos y comunidades autónomas ────────────────────────
  {
    id: "soc-3-spain-001",
    materia: "sociales",
    tema: "landscape.spain",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.spain.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.spain.q1.a" },
      { id: "b", textoKey: "exercises:social.spain.q1.b" },
      { id: "c", textoKey: "exercises:social.spain.q1.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-spain-002",
    materia: "sociales",
    tema: "landscape.spain",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.spain.q2.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "soc-3-spain-003",
    materia: "sociales",
    tema: "landscape.spain",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.spain.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.spain.q3.a" },
      { id: "b", textoKey: "exercises:social.spain.q3.b" },
      { id: "c", textoKey: "exercises:social.spain.q3.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "soc-3-spain-004",
    materia: "sociales",
    tema: "landscape.spain",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.spain.q4.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "false",
    imprimible: true,
  },
  {
    id: "soc-3-spain-005",
    materia: "sociales",
    tema: "landscape.spain",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.spain.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.spain.q5.a" },
      { id: "b", textoKey: "exercises:social.spain.q5.b" },
      { id: "c", textoKey: "exercises:social.spain.q5.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-spain-006",
    materia: "sociales",
    tema: "landscape.spain",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:social.spain.q6.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:social.spain.q6.l1" },
      { id: "l2", textoKey: "exercises:social.spain.q6.l2" },
      { id: "l3", textoKey: "exercises:social.spain.q6.l3" },
      { id: "r1", textoKey: "exercises:social.spain.q6.r1" },
      { id: "r2", textoKey: "exercises:social.spain.q6.r2" },
      { id: "r3", textoKey: "exercises:social.spain.q6.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r3", "l3:r1"],
    imprimible: true,
  },
  {
    id: "soc-3-spain-007",
    materia: "sociales",
    tema: "landscape.spain",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.spain.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.spain.q7.a" },
      { id: "b", textoKey: "exercises:social.spain.q7.b" },
      { id: "c", textoKey: "exercises:social.spain.q7.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "soc-3-spain-008",
    materia: "sociales",
    tema: "landscape.spain",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.spain.q8.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },

  // ─── La población y el trabajo ────────────────────────────────────────────
  {
    id: "soc-3-pop-001",
    materia: "sociales",
    tema: "society.population",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.pop.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.pop.q1.a" },
      { id: "b", textoKey: "exercises:social.pop.q1.b" },
      { id: "c", textoKey: "exercises:social.pop.q1.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-pop-002",
    materia: "sociales",
    tema: "society.population",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.pop.q2.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "soc-3-pop-003",
    materia: "sociales",
    tema: "society.population",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.pop.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.pop.q3.a" },
      { id: "b", textoKey: "exercises:social.pop.q3.b" },
      { id: "c", textoKey: "exercises:social.pop.q3.c" },
    ],
    respuestaCorrecta: "a",
    imprimible: true,
  },
  {
    id: "soc-3-pop-004",
    materia: "sociales",
    tema: "society.population",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.pop.q4.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "soc-3-pop-005",
    materia: "sociales",
    tema: "society.population",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.pop.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.pop.q5.a" },
      { id: "b", textoKey: "exercises:social.pop.q5.b" },
      { id: "c", textoKey: "exercises:social.pop.q5.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-pop-006",
    materia: "sociales",
    tema: "society.population",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:social.pop.q6.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:social.pop.q6.l1" },
      { id: "l2", textoKey: "exercises:social.pop.q6.l2" },
      { id: "l3", textoKey: "exercises:social.pop.q6.l3" },
      { id: "r1", textoKey: "exercises:social.pop.q6.r1" },
      { id: "r2", textoKey: "exercises:social.pop.q6.r2" },
      { id: "r3", textoKey: "exercises:social.pop.q6.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r3", "l3:r1"],
    imprimible: true,
  },
  {
    id: "soc-3-pop-007",
    materia: "sociales",
    tema: "society.population",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.pop.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.pop.q7.a" },
      { id: "b", textoKey: "exercises:social.pop.q7.b" },
      { id: "c", textoKey: "exercises:social.pop.q7.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-pop-008",
    materia: "sociales",
    tema: "society.population",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.pop.q8.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },

  // ─── El tiempo histórico ──────────────────────────────────────────────────
  {
    id: "soc-3-time-001",
    materia: "sociales",
    tema: "history.time",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.time.q1.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.time.q1.a" },
      { id: "b", textoKey: "exercises:social.time.q1.b" },
      { id: "c", textoKey: "exercises:social.time.q1.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-time-002",
    materia: "sociales",
    tema: "history.time",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.time.q2.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "soc-3-time-003",
    materia: "sociales",
    tema: "history.time",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.time.q3.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.time.q3.a" },
      { id: "b", textoKey: "exercises:social.time.q3.b" },
      { id: "c", textoKey: "exercises:social.time.q3.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-time-004",
    materia: "sociales",
    tema: "history.time",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.time.q4.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },
  {
    id: "soc-3-time-005",
    materia: "sociales",
    tema: "history.time",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.time.q5.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.time.q5.a" },
      { id: "b", textoKey: "exercises:social.time.q5.b" },
      { id: "c", textoKey: "exercises:social.time.q5.c" },
    ],
    respuestaCorrecta: "c",
    imprimible: true,
  },
  {
    id: "soc-3-time-006",
    materia: "sociales",
    tema: "history.time",
    nivel: "3",
    tipo: "emparejar",
    enunciadoKey: "exercises:social.time.q6.prompt",
    opciones: [
      { id: "l1", textoKey: "exercises:social.time.q6.l1" },
      { id: "l2", textoKey: "exercises:social.time.q6.l2" },
      { id: "l3", textoKey: "exercises:social.time.q6.l3" },
      { id: "r1", textoKey: "exercises:social.time.q6.r1" },
      { id: "r2", textoKey: "exercises:social.time.q6.r2" },
      { id: "r3", textoKey: "exercises:social.time.q6.r3" },
    ],
    respuestaCorrecta: ["l1:r2", "l2:r3", "l3:r1"],
    imprimible: true,
  },
  {
    id: "soc-3-time-007",
    materia: "sociales",
    tema: "history.time",
    nivel: "3",
    tipo: "opcion-multiple",
    enunciadoKey: "exercises:social.time.q7.prompt",
    opciones: [
      { id: "a", textoKey: "exercises:social.time.q7.a" },
      { id: "b", textoKey: "exercises:social.time.q7.b" },
      { id: "c", textoKey: "exercises:social.time.q7.c" },
    ],
    respuestaCorrecta: "b",
    imprimible: true,
  },
  {
    id: "soc-3-time-008",
    materia: "sociales",
    tema: "history.time",
    nivel: "3",
    tipo: "verdadero-falso",
    enunciadoKey: "exercises:social.time.q8.prompt",
    opciones: [
      { id: "true", textoKey: "quiz:answer.trueLabel" },
      { id: "false", textoKey: "quiz:answer.falseLabel" },
    ],
    respuestaCorrecta: "true",
    imprimible: true,
  },


  // ─── universe q9+ ──────────────────────────────────────────────────
  tfS("soc-3-universe-009", "earth_universe.universe", "exercises:social.universe.q9.prompt", "true"),
  mcS("soc-3-universe-010", "earth_universe.universe", "exercises:social.universe.q10.prompt", "a", "universe", "q10"),
  tfS("soc-3-universe-011", "earth_universe.universe", "exercises:social.universe.q11.prompt", "true"),
  mcS("soc-3-universe-012", "earth_universe.universe", "exercises:social.universe.q12.prompt", "b", "universe", "q12"),
  tfS("soc-3-universe-013", "earth_universe.universe", "exercises:social.universe.q13.prompt", "true"),
  mcS("soc-3-universe-014", "earth_universe.universe", "exercises:social.universe.q14.prompt", "c", "universe", "q14"),
  tfS("soc-3-universe-015", "earth_universe.universe", "exercises:social.universe.q15.prompt", "false"),
  mcS("soc-3-universe-016", "earth_universe.universe", "exercises:social.universe.q16.prompt", "b", "universe", "q16"),
  tfS("soc-3-universe-017", "earth_universe.universe", "exercises:social.universe.q17.prompt", "true"),
  mcS("soc-3-universe-018", "earth_universe.universe", "exercises:social.universe.q18.prompt", "a", "universe", "q18"),
  tfS("soc-3-universe-019", "earth_universe.universe", "exercises:social.universe.q19.prompt", "true"),
  mcS("soc-3-universe-020", "earth_universe.universe", "exercises:social.universe.q20.prompt", "c", "universe", "q20"),
  tfS("soc-3-universe-021", "earth_universe.universe", "exercises:social.universe.q21.prompt", "true"),
  mcS("soc-3-universe-022", "earth_universe.universe", "exercises:social.universe.q22.prompt", "b", "universe", "q22"),
  tfS("soc-3-universe-023", "earth_universe.universe", "exercises:social.universe.q23.prompt", "true"),
  mcS("soc-3-universe-024", "earth_universe.universe", "exercises:social.universe.q24.prompt", "a", "universe", "q24"),
  tfS("soc-3-universe-025", "earth_universe.universe", "exercises:social.universe.q25.prompt", "false"),
  mcS("soc-3-universe-026", "earth_universe.universe", "exercises:social.universe.q26.prompt", "b", "universe", "q26"),
  tfS("soc-3-universe-027", "earth_universe.universe", "exercises:social.universe.q27.prompt", "false"),
  mcS("soc-3-universe-028", "earth_universe.universe", "exercises:social.universe.q28.prompt", "c", "universe", "q28"),
  tfS("soc-3-universe-029", "earth_universe.universe", "exercises:social.universe.q29.prompt", "true"),
  mcS("soc-3-universe-030", "earth_universe.universe", "exercises:social.universe.q30.prompt", "a", "universe", "q30"),
  tfS("soc-3-universe-031", "earth_universe.universe", "exercises:social.universe.q31.prompt", "true"),
  mcS("soc-3-universe-032", "earth_universe.universe", "exercises:social.universe.q32.prompt", "c", "universe", "q32"),
  tfS("soc-3-universe-033", "earth_universe.universe", "exercises:social.universe.q33.prompt", "true"),
  mcS("soc-3-universe-034", "earth_universe.universe", "exercises:social.universe.q34.prompt", "b", "universe", "q34"),
  tfS("soc-3-universe-035", "earth_universe.universe", "exercises:social.universe.q35.prompt", "true"),
  mcS("soc-3-universe-036", "earth_universe.universe", "exercises:social.universe.q36.prompt", "a", "universe", "q36"),
  tfS("soc-3-universe-037", "earth_universe.universe", "exercises:social.universe.q37.prompt", "true"),
  mcS("soc-3-universe-038", "earth_universe.universe", "exercises:social.universe.q38.prompt", "c", "universe", "q38"),
  tfS("soc-3-universe-039", "earth_universe.universe", "exercises:social.universe.q39.prompt", "true"),
  mcS("soc-3-universe-040", "earth_universe.universe", "exercises:social.universe.q40.prompt", "b", "universe", "q40"),
  tfS("soc-3-universe-041", "earth_universe.universe", "exercises:social.universe.q41.prompt", "true"),
  mcS("soc-3-universe-042", "earth_universe.universe", "exercises:social.universe.q42.prompt", "a", "universe", "q42"),
  tfS("soc-3-universe-043", "earth_universe.universe", "exercises:social.universe.q43.prompt", "true"),
  mcS("soc-3-universe-044", "earth_universe.universe", "exercises:social.universe.q44.prompt", "b", "universe", "q44"),
  tfS("soc-3-universe-045", "earth_universe.universe", "exercises:social.universe.q45.prompt", "true"),
  mcS("soc-3-universe-046", "earth_universe.universe", "exercises:social.universe.q46.prompt", "c", "universe", "q46"),
  tfS("soc-3-universe-047", "earth_universe.universe", "exercises:social.universe.q47.prompt", "true"),
  mcS("soc-3-universe-048", "earth_universe.universe", "exercises:social.universe.q48.prompt", "a", "universe", "q48"),
  tfS("soc-3-universe-049", "earth_universe.universe", "exercises:social.universe.q49.prompt", "true"),
  mcS("soc-3-universe-050", "earth_universe.universe", "exercises:social.universe.q50.prompt", "b", "universe", "q50"),
  tfS("soc-3-universe-051", "earth_universe.universe", "exercises:social.universe.q51.prompt", "true"),
  mcS("soc-3-universe-052", "earth_universe.universe", "exercises:social.universe.q52.prompt", "c", "universe", "q52"),

  // ─── maps q9+ ──────────────────────────────────────────────────
  tfS("soc-3-maps-009", "landscape.maps", "exercises:social.maps.q9.prompt", "true"),
  mcS("soc-3-maps-010", "landscape.maps", "exercises:social.maps.q10.prompt", "c", "maps", "q10"),
  tfS("soc-3-maps-011", "landscape.maps", "exercises:social.maps.q11.prompt", "false"),
  mcS("soc-3-maps-012", "landscape.maps", "exercises:social.maps.q12.prompt", "b", "maps", "q12"),
  tfS("soc-3-maps-013", "landscape.maps", "exercises:social.maps.q13.prompt", "true"),
  mcS("soc-3-maps-014", "landscape.maps", "exercises:social.maps.q14.prompt", "c", "maps", "q14"),
  tfS("soc-3-maps-015", "landscape.maps", "exercises:social.maps.q15.prompt", "false"),
  mcS("soc-3-maps-016", "landscape.maps", "exercises:social.maps.q16.prompt", "a", "maps", "q16"),
  tfS("soc-3-maps-017", "landscape.maps", "exercises:social.maps.q17.prompt", "true"),
  mcS("soc-3-maps-018", "landscape.maps", "exercises:social.maps.q18.prompt", "b", "maps", "q18"),
  tfS("soc-3-maps-019", "landscape.maps", "exercises:social.maps.q19.prompt", "true"),
  mcS("soc-3-maps-020", "landscape.maps", "exercises:social.maps.q20.prompt", "c", "maps", "q20"),
  tfS("soc-3-maps-021", "landscape.maps", "exercises:social.maps.q21.prompt", "true"),
  mcS("soc-3-maps-022", "landscape.maps", "exercises:social.maps.q22.prompt", "a", "maps", "q22"),
  tfS("soc-3-maps-023", "landscape.maps", "exercises:social.maps.q23.prompt", "true"),
  mcS("soc-3-maps-024", "landscape.maps", "exercises:social.maps.q24.prompt", "b", "maps", "q24"),
  tfS("soc-3-maps-025", "landscape.maps", "exercises:social.maps.q25.prompt", "true"),
  mcS("soc-3-maps-026", "landscape.maps", "exercises:social.maps.q26.prompt", "c", "maps", "q26"),
  tfS("soc-3-maps-027", "landscape.maps", "exercises:social.maps.q27.prompt", "false"),
  mcS("soc-3-maps-028", "landscape.maps", "exercises:social.maps.q28.prompt", "a", "maps", "q28"),
  tfS("soc-3-maps-029", "landscape.maps", "exercises:social.maps.q29.prompt", "true"),
  mcS("soc-3-maps-030", "landscape.maps", "exercises:social.maps.q30.prompt", "b", "maps", "q30"),
  tfS("soc-3-maps-031", "landscape.maps", "exercises:social.maps.q31.prompt", "true"),
  mcS("soc-3-maps-032", "landscape.maps", "exercises:social.maps.q32.prompt", "c", "maps", "q32"),
  tfS("soc-3-maps-033", "landscape.maps", "exercises:social.maps.q33.prompt", "true"),
  mcS("soc-3-maps-034", "landscape.maps", "exercises:social.maps.q34.prompt", "a", "maps", "q34"),
  tfS("soc-3-maps-035", "landscape.maps", "exercises:social.maps.q35.prompt", "true"),
  mcS("soc-3-maps-036", "landscape.maps", "exercises:social.maps.q36.prompt", "b", "maps", "q36"),
  tfS("soc-3-maps-037", "landscape.maps", "exercises:social.maps.q37.prompt", "false"),
  mcS("soc-3-maps-038", "landscape.maps", "exercises:social.maps.q38.prompt", "c", "maps", "q38"),
  tfS("soc-3-maps-039", "landscape.maps", "exercises:social.maps.q39.prompt", "true"),
  mcS("soc-3-maps-040", "landscape.maps", "exercises:social.maps.q40.prompt", "a", "maps", "q40"),
  tfS("soc-3-maps-041", "landscape.maps", "exercises:social.maps.q41.prompt", "true"),
  mcS("soc-3-maps-042", "landscape.maps", "exercises:social.maps.q42.prompt", "b", "maps", "q42"),
  tfS("soc-3-maps-043", "landscape.maps", "exercises:social.maps.q43.prompt", "true"),
  mcS("soc-3-maps-044", "landscape.maps", "exercises:social.maps.q44.prompt", "c", "maps", "q44"),
  tfS("soc-3-maps-045", "landscape.maps", "exercises:social.maps.q45.prompt", "true"),
  mcS("soc-3-maps-046", "landscape.maps", "exercises:social.maps.q46.prompt", "a", "maps", "q46"),
  tfS("soc-3-maps-047", "landscape.maps", "exercises:social.maps.q47.prompt", "true"),
  mcS("soc-3-maps-048", "landscape.maps", "exercises:social.maps.q48.prompt", "b", "maps", "q48"),
  tfS("soc-3-maps-049", "landscape.maps", "exercises:social.maps.q49.prompt", "true"),
  mcS("soc-3-maps-050", "landscape.maps", "exercises:social.maps.q50.prompt", "c", "maps", "q50"),
  tfS("soc-3-maps-051", "landscape.maps", "exercises:social.maps.q51.prompt", "true"),

  // ─── spain q9+ ──────────────────────────────────────────────────
  tfS("soc-3-spain-009", "landscape.spain", "exercises:social.spain.q9.prompt", "true"),
  mcS("soc-3-spain-010", "landscape.spain", "exercises:social.spain.q10.prompt", "c", "spain", "q10"),
  tfS("soc-3-spain-011", "landscape.spain", "exercises:social.spain.q11.prompt", "true"),
  mcS("soc-3-spain-012", "landscape.spain", "exercises:social.spain.q12.prompt", "a", "spain", "q12"),
  tfS("soc-3-spain-013", "landscape.spain", "exercises:social.spain.q13.prompt", "true"),
  mcS("soc-3-spain-014", "landscape.spain", "exercises:social.spain.q14.prompt", "b", "spain", "q14"),
  tfS("soc-3-spain-015", "landscape.spain", "exercises:social.spain.q15.prompt", "true"),
  mcS("soc-3-spain-016", "landscape.spain", "exercises:social.spain.q16.prompt", "c", "spain", "q16"),
  tfS("soc-3-spain-017", "landscape.spain", "exercises:social.spain.q17.prompt", "true"),
  mcS("soc-3-spain-018", "landscape.spain", "exercises:social.spain.q18.prompt", "a", "spain", "q18"),
  tfS("soc-3-spain-019", "landscape.spain", "exercises:social.spain.q19.prompt", "true"),
  mcS("soc-3-spain-020", "landscape.spain", "exercises:social.spain.q20.prompt", "b", "spain", "q20"),
  tfS("soc-3-spain-021", "landscape.spain", "exercises:social.spain.q21.prompt", "true"),
  mcS("soc-3-spain-022", "landscape.spain", "exercises:social.spain.q22.prompt", "c", "spain", "q22"),
  tfS("soc-3-spain-023", "landscape.spain", "exercises:social.spain.q23.prompt", "true"),
  mcS("soc-3-spain-024", "landscape.spain", "exercises:social.spain.q24.prompt", "b", "spain", "q24"),
  tfS("soc-3-spain-025", "landscape.spain", "exercises:social.spain.q25.prompt", "true"),
  mcS("soc-3-spain-026", "landscape.spain", "exercises:social.spain.q26.prompt", "c", "spain", "q26"),
  tfS("soc-3-spain-027", "landscape.spain", "exercises:social.spain.q27.prompt", "true"),
  mcS("soc-3-spain-028", "landscape.spain", "exercises:social.spain.q28.prompt", "a", "spain", "q28"),
  tfS("soc-3-spain-029", "landscape.spain", "exercises:social.spain.q29.prompt", "true"),
  mcS("soc-3-spain-030", "landscape.spain", "exercises:social.spain.q30.prompt", "b", "spain", "q30"),
  tfS("soc-3-spain-031", "landscape.spain", "exercises:social.spain.q31.prompt", "true"),
  mcS("soc-3-spain-032", "landscape.spain", "exercises:social.spain.q32.prompt", "c", "spain", "q32"),
  tfS("soc-3-spain-033", "landscape.spain", "exercises:social.spain.q33.prompt", "true"),
  mcS("soc-3-spain-034", "landscape.spain", "exercises:social.spain.q34.prompt", "a", "spain", "q34"),
  tfS("soc-3-spain-035", "landscape.spain", "exercises:social.spain.q35.prompt", "true"),
  mcS("soc-3-spain-036", "landscape.spain", "exercises:social.spain.q36.prompt", "b", "spain", "q36"),
  tfS("soc-3-spain-037", "landscape.spain", "exercises:social.spain.q37.prompt", "true"),
  mcS("soc-3-spain-038", "landscape.spain", "exercises:social.spain.q38.prompt", "c", "spain", "q38"),
  tfS("soc-3-spain-039", "landscape.spain", "exercises:social.spain.q39.prompt", "true"),
  mcS("soc-3-spain-040", "landscape.spain", "exercises:social.spain.q40.prompt", "a", "spain", "q40"),
  tfS("soc-3-spain-041", "landscape.spain", "exercises:social.spain.q41.prompt", "true"),
  mcS("soc-3-spain-042", "landscape.spain", "exercises:social.spain.q42.prompt", "b", "spain", "q42"),
  tfS("soc-3-spain-043", "landscape.spain", "exercises:social.spain.q43.prompt", "true"),
  mcS("soc-3-spain-044", "landscape.spain", "exercises:social.spain.q44.prompt", "b", "spain", "q44"),
  tfS("soc-3-spain-045", "landscape.spain", "exercises:social.spain.q45.prompt", "true"),
  mcS("soc-3-spain-046", "landscape.spain", "exercises:social.spain.q46.prompt", "a", "spain", "q46"),
  tfS("soc-3-spain-047", "landscape.spain", "exercises:social.spain.q47.prompt", "true"),
  mcS("soc-3-spain-048", "landscape.spain", "exercises:social.spain.q48.prompt", "b", "spain", "q48"),
  tfS("soc-3-spain-049", "landscape.spain", "exercises:social.spain.q49.prompt", "true"),
  mcS("soc-3-spain-050", "landscape.spain", "exercises:social.spain.q50.prompt", "c", "spain", "q50"),
  tfS("soc-3-spain-051", "landscape.spain", "exercises:social.spain.q51.prompt", "true"),

  // ─── pop q9+ ──────────────────────────────────────────────────
  tfS("soc-3-pop-009", "society.population", "exercises:social.pop.q9.prompt", "true"),
  mcS("soc-3-pop-010", "society.population", "exercises:social.pop.q10.prompt", "b", "pop", "q10"),
  tfS("soc-3-pop-011", "society.population", "exercises:social.pop.q11.prompt", "true"),
  mcS("soc-3-pop-012", "society.population", "exercises:social.pop.q12.prompt", "c", "pop", "q12"),
  tfS("soc-3-pop-013", "society.population", "exercises:social.pop.q13.prompt", "true"),
  mcS("soc-3-pop-014", "society.population", "exercises:social.pop.q14.prompt", "a", "pop", "q14"),
  tfS("soc-3-pop-015", "society.population", "exercises:social.pop.q15.prompt", "true"),
  mcS("soc-3-pop-016", "society.population", "exercises:social.pop.q16.prompt", "b", "pop", "q16"),
  tfS("soc-3-pop-017", "society.population", "exercises:social.pop.q17.prompt", "true"),
  mcS("soc-3-pop-018", "society.population", "exercises:social.pop.q18.prompt", "c", "pop", "q18"),
  tfS("soc-3-pop-019", "society.population", "exercises:social.pop.q19.prompt", "true"),
  mcS("soc-3-pop-020", "society.population", "exercises:social.pop.q20.prompt", "a", "pop", "q20"),
  tfS("soc-3-pop-021", "society.population", "exercises:social.pop.q21.prompt", "true"),
  mcS("soc-3-pop-022", "society.population", "exercises:social.pop.q22.prompt", "b", "pop", "q22"),
  tfS("soc-3-pop-023", "society.population", "exercises:social.pop.q23.prompt", "true"),
  mcS("soc-3-pop-024", "society.population", "exercises:social.pop.q24.prompt", "c", "pop", "q24"),
  tfS("soc-3-pop-025", "society.population", "exercises:social.pop.q25.prompt", "true"),
  mcS("soc-3-pop-026", "society.population", "exercises:social.pop.q26.prompt", "a", "pop", "q26"),
  tfS("soc-3-pop-027", "society.population", "exercises:social.pop.q27.prompt", "true"),
  mcS("soc-3-pop-028", "society.population", "exercises:social.pop.q28.prompt", "b", "pop", "q28"),
  tfS("soc-3-pop-029", "society.population", "exercises:social.pop.q29.prompt", "true"),
  mcS("soc-3-pop-030", "society.population", "exercises:social.pop.q30.prompt", "c", "pop", "q30"),
  tfS("soc-3-pop-031", "society.population", "exercises:social.pop.q31.prompt", "true"),
  mcS("soc-3-pop-032", "society.population", "exercises:social.pop.q32.prompt", "a", "pop", "q32"),
  tfS("soc-3-pop-033", "society.population", "exercises:social.pop.q33.prompt", "true"),
  mcS("soc-3-pop-034", "society.population", "exercises:social.pop.q34.prompt", "b", "pop", "q34"),
  tfS("soc-3-pop-035", "society.population", "exercises:social.pop.q35.prompt", "true"),
  mcS("soc-3-pop-036", "society.population", "exercises:social.pop.q36.prompt", "c", "pop", "q36"),
  tfS("soc-3-pop-037", "society.population", "exercises:social.pop.q37.prompt", "true"),
  mcS("soc-3-pop-038", "society.population", "exercises:social.pop.q38.prompt", "a", "pop", "q38"),
  tfS("soc-3-pop-039", "society.population", "exercises:social.pop.q39.prompt", "true"),
  mcS("soc-3-pop-040", "society.population", "exercises:social.pop.q40.prompt", "b", "pop", "q40"),
  tfS("soc-3-pop-041", "society.population", "exercises:social.pop.q41.prompt", "true"),
  mcS("soc-3-pop-042", "society.population", "exercises:social.pop.q42.prompt", "c", "pop", "q42"),
  tfS("soc-3-pop-043", "society.population", "exercises:social.pop.q43.prompt", "true"),
  mcS("soc-3-pop-044", "society.population", "exercises:social.pop.q44.prompt", "a", "pop", "q44"),
  tfS("soc-3-pop-045", "society.population", "exercises:social.pop.q45.prompt", "true"),
  mcS("soc-3-pop-046", "society.population", "exercises:social.pop.q46.prompt", "b", "pop", "q46"),
  tfS("soc-3-pop-047", "society.population", "exercises:social.pop.q47.prompt", "true"),
  mcS("soc-3-pop-048", "society.population", "exercises:social.pop.q48.prompt", "c", "pop", "q48"),
  tfS("soc-3-pop-049", "society.population", "exercises:social.pop.q49.prompt", "true"),
  mcS("soc-3-pop-050", "society.population", "exercises:social.pop.q50.prompt", "a", "pop", "q50"),
  tfS("soc-3-pop-051", "society.population", "exercises:social.pop.q51.prompt", "true"),

  // ─── time q9+ ──────────────────────────────────────────────────
  tfS("soc-3-time-009", "history.time", "exercises:social.time.q9.prompt", "true"),
  mcS("soc-3-time-010", "history.time", "exercises:social.time.q10.prompt", "b", "time", "q10"),
  tfS("soc-3-time-011", "history.time", "exercises:social.time.q11.prompt", "true"),
  mcS("soc-3-time-012", "history.time", "exercises:social.time.q12.prompt", "c", "time", "q12"),
  tfS("soc-3-time-013", "history.time", "exercises:social.time.q13.prompt", "true"),
  mcS("soc-3-time-014", "history.time", "exercises:social.time.q14.prompt", "b", "time", "q14"),
  tfS("soc-3-time-015", "history.time", "exercises:social.time.q15.prompt", "true"),
  mcS("soc-3-time-016", "history.time", "exercises:social.time.q16.prompt", "a", "time", "q16"),
  tfS("soc-3-time-017", "history.time", "exercises:social.time.q17.prompt", "true"),
  mcS("soc-3-time-018", "history.time", "exercises:social.time.q18.prompt", "b", "time", "q18"),
  tfS("soc-3-time-019", "history.time", "exercises:social.time.q19.prompt", "true"),
  mcS("soc-3-time-020", "history.time", "exercises:social.time.q20.prompt", "c", "time", "q20"),
  tfS("soc-3-time-021", "history.time", "exercises:social.time.q21.prompt", "true"),
  mcS("soc-3-time-022", "history.time", "exercises:social.time.q22.prompt", "a", "time", "q22"),
  tfS("soc-3-time-023", "history.time", "exercises:social.time.q23.prompt", "true"),
  mcS("soc-3-time-024", "history.time", "exercises:social.time.q24.prompt", "b", "time", "q24"),
  tfS("soc-3-time-025", "history.time", "exercises:social.time.q25.prompt", "true"),
  mcS("soc-3-time-026", "history.time", "exercises:social.time.q26.prompt", "c", "time", "q26"),
  tfS("soc-3-time-027", "history.time", "exercises:social.time.q27.prompt", "true"),
  mcS("soc-3-time-028", "history.time", "exercises:social.time.q28.prompt", "a", "time", "q28"),
  tfS("soc-3-time-029", "history.time", "exercises:social.time.q29.prompt", "true"),
  mcS("soc-3-time-030", "history.time", "exercises:social.time.q30.prompt", "b", "time", "q30"),
  tfS("soc-3-time-031", "history.time", "exercises:social.time.q31.prompt", "true"),
  mcS("soc-3-time-032", "history.time", "exercises:social.time.q32.prompt", "c", "time", "q32"),
  tfS("soc-3-time-033", "history.time", "exercises:social.time.q33.prompt", "true"),
  mcS("soc-3-time-034", "history.time", "exercises:social.time.q34.prompt", "a", "time", "q34"),
  tfS("soc-3-time-035", "history.time", "exercises:social.time.q35.prompt", "true"),
  mcS("soc-3-time-036", "history.time", "exercises:social.time.q36.prompt", "b", "time", "q36"),
  tfS("soc-3-time-037", "history.time", "exercises:social.time.q37.prompt", "true"),
  mcS("soc-3-time-038", "history.time", "exercises:social.time.q38.prompt", "c", "time", "q38"),
  tfS("soc-3-time-039", "history.time", "exercises:social.time.q39.prompt", "true"),
  mcS("soc-3-time-040", "history.time", "exercises:social.time.q40.prompt", "a", "time", "q40"),
  tfS("soc-3-time-041", "history.time", "exercises:social.time.q41.prompt", "true"),
  mcS("soc-3-time-042", "history.time", "exercises:social.time.q42.prompt", "b", "time", "q42"),
  tfS("soc-3-time-043", "history.time", "exercises:social.time.q43.prompt", "true"),
  mcS("soc-3-time-044", "history.time", "exercises:social.time.q44.prompt", "c", "time", "q44"),
  tfS("soc-3-time-045", "history.time", "exercises:social.time.q45.prompt", "true"),
  mcS("soc-3-time-046", "history.time", "exercises:social.time.q46.prompt", "b", "time", "q46"),
  tfS("soc-3-time-047", "history.time", "exercises:social.time.q47.prompt", "true"),
  mcS("soc-3-time-048", "history.time", "exercises:social.time.q48.prompt", "a", "time", "q48"),
  tfS("soc-3-time-049", "history.time", "exercises:social.time.q49.prompt", "true"),
  mcS("soc-3-time-050", "history.time", "exercises:social.time.q50.prompt", "b", "time", "q50"),
  tfS("soc-3-time-051", "history.time", "exercises:social.time.q51.prompt", "false"),
];
